// Generated by scripts/generate-postgres-payments.cjs from StripeStore; do not edit.
import {PostgresBillingDatabase} from "./PostgresBillingDatabase";
import type {StripeStore} from "./stripe";
type OriginalContract=Omit<StripeStore,"db">;
type AsyncPaymentContract={[K in keyof OriginalContract]:OriginalContract[K] extends (...args:infer A)=>infer R ? (...args:A)=>Promise<R>:never};
// ---------- store ----------
export class PostgresStripeStore implements AsyncPaymentContract {
    private constructor(private db: PostgresBillingDatabase) { }
    async customerOf(accountId: string): Promise<string | null> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare(`SELECT customer_id FROM stripe_customers WHERE account_id = ?`).get(accountId)) as {
                customer_id: string;
            } | undefined)?.customer_id ?? null;
        });
    }
    async accountOfCustomer(customerId: string): Promise<string | null> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare(`SELECT account_id FROM stripe_customers WHERE customer_id = ?`).get(customerId)) as {
                account_id: string;
            } | undefined)?.account_id ?? null;
        });
    }
    async saveCustomer(accountId: string, customerId: string, email: string | null): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`INSERT OR IGNORE INTO stripe_customers (account_id, customer_id, email, created_at) VALUES (?, ?, ?, ?)`).run(accountId, customerId, email, Date.now()));
        });
    }
    /** true when the event is new (recorded now); false for a replay already handled. */
    async claimEvent(id: string, type: string): Promise<boolean> {
        return this.db.transaction(async () => {
            const prior = (await this.db.prepare(`SELECT status FROM stripe_events WHERE id = ?`).get(id)) as {
                status: string;
            } | undefined;
            if (prior && prior.status === "processed")
                return false;
            if (!prior)
                (await this.db.prepare(`INSERT INTO stripe_events (id, type, received_at, status) VALUES (?, ?, ?, 'received')`).run(id, type, Date.now()));
            return true;
        });
    }
    async finishEvent(id: string, status: "processed" | "failed" | "ignored", error?: string): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`UPDATE stripe_events SET status = ?, error = ?, processed_at = ? WHERE id = ?`).run(status, error ?? null, Date.now(), id));
        });
    }
    async eventStatus(id: string): Promise<string | null> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare(`SELECT status FROM stripe_events WHERE id = ?`).get(id)) as {
                status: string;
            } | undefined)?.status ?? null;
        });
    }
    async saveCheckout(row: {
        sessionId: string;
        accountId: string;
        kind: "subscription" | "topup";
        item: string;
        period?: string;
    }): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`INSERT OR IGNORE INTO stripe_checkouts (session_id, account_id, kind, item, period, status, created_at) VALUES (?, ?, ?, ?, ?, 'open', ?)`)
                .run(row.sessionId, row.accountId, row.kind, row.item, row.period ?? null, Date.now()));
        });
    }
    async checkout(sessionId: string) {
        return this.db.transaction(async () => {
            return (await this.db.prepare(`SELECT * FROM stripe_checkouts WHERE session_id = ?`).get(sessionId)) as {
                session_id: string;
                account_id: string;
                kind: string;
                item: string;
                status: string;
                payment_intent: string | null;
            } | undefined;
        });
    }
    async checkoutByPaymentIntent(pi: string) {
        return this.db.transaction(async () => {
            return (await this.db.prepare(`SELECT * FROM stripe_checkouts WHERE payment_intent = ?`).get(pi)) as {
                account_id: string;
                kind: string;
                item: string;
            } | undefined;
        });
    }
    async completeCheckout(sessionId: string, fields: {
        paymentIntent?: string | null;
        subscriptionId?: string | null;
    }): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`UPDATE stripe_checkouts SET status = 'complete', payment_intent = COALESCE(?, payment_intent), subscription_id = COALESCE(?, subscription_id) WHERE session_id = ?`)
                .run(fields.paymentIntent ?? null, fields.subscriptionId ?? null, sessionId));
        });
    }
    async saveSubscription(s: {
        subscriptionId: string;
        accountId: string;
        planId: string;
        status: string;
        periodStart?: number;
        periodEnd?: number;
        cancelAtPeriodEnd?: boolean;
    }): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`INSERT INTO stripe_subscriptions (subscription_id, account_id, plan_id, status, period_start, period_end, cancel_at_period_end, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT(subscription_id) DO UPDATE SET plan_id = excluded.plan_id, status = excluded.status,
         period_start = COALESCE(excluded.period_start, period_start), period_end = COALESCE(excluded.period_end, period_end),
         cancel_at_period_end = excluded.cancel_at_period_end, updated_at = excluded.updated_at`).run(s.subscriptionId, s.accountId, s.planId, s.status, s.periodStart ?? null, s.periodEnd ?? null, s.cancelAtPeriodEnd ? 1 : 0, Date.now()));
        });
    }
    async subscription(id: string) {
        return this.db.transaction(async () => {
            return (await this.db.prepare(`SELECT * FROM stripe_subscriptions WHERE subscription_id = ?`).get(id)) as {
                subscription_id: string;
                account_id: string;
                plan_id: string;
                status: string;
            } | undefined;
        });
    }
    /** The account's newest Stripe subscription (any status). */
    async latestSubscription(accountId: string) {
        return this.db.transaction(async () => {
            return (await this.db.prepare(`SELECT * FROM stripe_subscriptions WHERE account_id = ? ORDER BY updated_at DESC LIMIT 1`).get(accountId)) as {
                subscription_id: string;
                account_id: string;
                plan_id: string;
                status: string;
                period_start: number | null;
                period_end: number | null;
                cancel_at_period_end: number;
            } | undefined;
        });
    }
    async periodOf(subscriptionId: string): Promise<"monthly" | "yearly" | null> {
        return this.db.transaction(async () => {
            const r = (await this.db.prepare(`SELECT period FROM stripe_checkouts WHERE subscription_id = ? ORDER BY created_at DESC LIMIT 1`).get(subscriptionId)) as {
                period: string | null;
            } | undefined;
            return r?.period === "yearly" ? "yearly" : r?.period === "monthly" ? "monthly" : null;
        });
    }
    async failedEvents(sinceMs: number) {
        return this.db.transaction(async () => {
            return (await this.db.prepare(`SELECT id, type, received_at, error FROM stripe_events WHERE status = 'failed' AND received_at >= ? ORDER BY received_at DESC LIMIT 50`).all(sinceMs)) as {
                id: string;
                type: string;
                received_at: number;
                error: string | null;
            }[];
        });
    }
    async eventStats(sinceMs: number) {
        return this.db.transaction(async () => {
            return (await this.db.prepare(`SELECT status, COUNT(*) AS n, MAX(received_at) AS last FROM stripe_events WHERE received_at >= ? GROUP BY status`).all(sinceMs)) as {
                status: string;
                n: number;
                last: number;
            }[];
        });
    }
    async lastEventAt(): Promise<number | null> {
        return this.db.transaction(async () => {
            return (((await this.db.prepare(`SELECT MAX(received_at) AS t FROM stripe_events`).get()) as {
                t: number | null;
            }).t) ?? null;
        });
    }
    async recentEvents(limit = 50) {
        return this.db.transaction(async () => {
            return (await this.db.prepare(`SELECT * FROM stripe_events ORDER BY received_at DESC LIMIT ?`).all(limit));
        });
    }
static fromDatabase(database: PostgresBillingDatabase): PostgresStripeStore { return new PostgresStripeStore(database); }
}
