import { Pool, type PoolClient } from "pg";
import { STRIPE_INDEXES, STRIPE_TABLES, STRIPE_UNIQUE_KEYS } from "./stripeSchema";
import { stripeSnapshotFingerprint, validateStripeSnapshot, type StripeSnapshot, type StripeRow } from "./StripeStorageSnapshot";

const LOCK = "SELECT pg_advisory_xact_lock(730021, 4)";

/** Complete Stripe payment migration target. Live payment routing is deliberately not switched here. */
export class PostgresStripeStorage {
  private pool: Pool;
  constructor(url: string) {
    if (!url) throw new Error("Stripe payment storage requires a PostgreSQL URL");
    this.pool = new Pool({ connectionString:url, max:4, connectionTimeoutMillis:5000,
      statement_timeout:10000, lock_timeout:5000, idleTimeoutMillis:30000 });
  }

  private async transaction<T>(operation: (client:PoolClient) => Promise<T>): Promise<T> {
    const client = await this.pool.connect();
    let discard: Error | undefined;
    try {
      await client.query("BEGIN");
      await client.query(LOCK);
      const result = await operation(client);
      await client.query("COMMIT");
      return result;
    } catch (error) {
      try { await client.query("ROLLBACK"); } catch { discard = new Error("Stripe payment transaction connection failed"); }
      throw error;
    } finally { client.release(discard); }
  }

  async init(): Promise<void> {
    await this.transaction(async client => {
      await client.query("CREATE SCHEMA IF NOT EXISTS orvyn_payments");
      await client.query("CREATE TABLE IF NOT EXISTS orvyn_payments.migrations(version INTEGER PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())");
      const applied = await client.query("SELECT version FROM orvyn_payments.migrations ORDER BY version");
      if (applied.rows.some(row => row.version !== 1)) throw new Error("Unsupported Stripe payment storage version");
      if (applied.rowCount) return;
      for (const table of STRIPE_TABLES) {
        // SQL comes exclusively from the checked-in contract, never from imported files.
        await client.query(table.sql.replace(/CREATE TABLE(?: IF NOT EXISTS)?\s+\w+/i,
          `CREATE TABLE orvyn_payments."${table.name}"`).replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g,
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY").replace(/\bINTEGER\b/g, "BIGINT"));
      }
      for (const sql of STRIPE_INDEXES) await client.query(sql.replace(/\bON\s+(\w+)/i, 'ON orvyn_payments."$1"'));
      await client.query("CREATE TABLE orvyn_payments.imports(fingerprint TEXT PRIMARY KEY, imported_at TIMESTAMPTZ NOT NULL DEFAULT now())");
      await client.query("INSERT INTO orvyn_payments.migrations(version) VALUES (1)");
    });
  }

  private async read(client: PoolClient): Promise<StripeSnapshot> {
    // Keep the cross-table view consistent even if an operator writes outside this repository.
    await client.query(`LOCK TABLE ${STRIPE_TABLES.map(table => `orvyn_payments."${table.name}"`).join(",")} IN SHARE ROW EXCLUSIVE MODE`);
    const version = await client.query("SELECT version FROM orvyn_payments.migrations ORDER BY version");
    if (version.rows.length !== 1 || version.rows[0].version !== 1) throw new Error("Unsupported Stripe payment storage version");
    const inventory=await client.query("SELECT table_name FROM information_schema.tables WHERE table_schema='orvyn_payments' ORDER BY table_name");
    if(JSON.stringify(inventory.rows.map(row=>row.table_name))!==JSON.stringify([...STRIPE_TABLES.map(t=>t.name),"imports","migrations"].sort())) throw new Error("PostgreSQL payment inventory differs");
    const columns = await client.query("SELECT table_name,column_name,data_type,is_nullable FROM information_schema.columns WHERE table_schema='orvyn_payments'");
    const keys = await client.query(`SELECT c.relname AS table_name,array_agg(a.attname::text ORDER BY k.ord) AS columns
      FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace
      CROSS JOIN LATERAL unnest(con.conkey) WITH ORDINALITY k(attnum,ord)
      JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum=k.attnum
      WHERE n.nspname='orvyn_payments' AND con.contype IN ('p','u') GROUP BY c.relname,con.oid`);
    for (const table of STRIPE_TABLES) {
      const actual = columns.rows.filter(row => row.table_name === table.name);
      if (actual.length !== table.columns.length || table.columns.some(column => !actual.some(row =>
        row.column_name === column.name && row.data_type === (column.type === "INTEGER" ? "bigint" : "text") &&
        row.is_nullable === (column.notNull || column.primaryKey ? "NO" : "YES")))) {
        throw new Error(`PostgreSQL Stripe payment schema differs: ${table.name}`);
      }
      const canonical = (values: readonly (readonly string[])[]) => JSON.stringify(Array.from(new Set(values.map(value => JSON.stringify(value)))).sort());
      if (canonical(keys.rows.filter(row => row.table_name === table.name).map(row => row.columns)) !== canonical(STRIPE_UNIQUE_KEYS[table.name])) {
        throw new Error(`PostgreSQL Stripe payment uniqueness differs: ${table.name}`);
      }
    }
    const snapshot: StripeSnapshot = {};
    for (const table of STRIPE_TABLES) {
      const result = await client.query(`SELECT * FROM orvyn_payments."${table.name}"`);
      snapshot[table.name] = result.rows.map(row => {
        const normalized: StripeRow = {};
        for (const column of table.columns) normalized[column.name] = row[column.name] === null ? null :
          column.type === "INTEGER" ? Number(row[column.name]) : row[column.name];
        return normalized;
      });
    }
    validateStripeSnapshot(snapshot);
    return snapshot;
  }

  async verify(snapshot: StripeSnapshot): Promise<{ matches:boolean; fingerprint:string; counts:Record<string,number> }> {
    const fingerprint = stripeSnapshotFingerprint(snapshot);
    return this.transaction(async client => {
      const stored = await this.read(client);
      return { matches:stripeSnapshotFingerprint(stored) === fingerprint, fingerprint,
        counts:Object.fromEntries(STRIPE_TABLES.map(table => [table.name, stored[table.name].length])) };
    });
  }

  /** Private migration/restore tooling only: the returned records contain account secrets. */
  async exportSnapshot(): Promise<StripeSnapshot> { return this.transaction(client => this.read(client)); }

  /** Seed only an empty target; repeat of identical data is safe, differing data is never overwritten. */
  async importSnapshot(snapshot: StripeSnapshot): Promise<{ imported:boolean; fingerprint:string }> {
    const fingerprint = stripeSnapshotFingerprint(snapshot);
    return this.transaction(async client => {
      const current = await this.read(client);
      const imported = await client.query("SELECT 1 FROM orvyn_payments.imports LIMIT 1");
      const occupied = imported.rowCount || STRIPE_TABLES.some(table => current[table.name].length > 0);
      if (occupied) {
        if (stripeSnapshotFingerprint(current) !== fingerprint) throw new Error("Stripe payment target differs; refusing to overwrite existing records");
        return { imported:false, fingerprint };
      }
      for (const table of STRIPE_TABLES) {
        const columns = table.columns.map(column => `"${column.name}"`).join(",");
        const placeholders = table.columns.map((_, index) => `$${index + 1}`).join(",");
        for (const row of snapshot[table.name]) await client.query(
          `INSERT INTO orvyn_payments."${table.name}"(${columns}) VALUES (${placeholders})`, table.columns.map(column => row[column.name]));
      }
      if (stripeSnapshotFingerprint(await this.read(client)) !== fingerprint) throw new Error("Stripe payment content verification failed");
      await client.query("INSERT INTO orvyn_payments.imports(fingerprint) VALUES ($1)", [fingerprint]);
      return { imported:true, fingerprint };
    });
  }

  async close(): Promise<void> { await this.pool.end(); }
}
