import { LEGACY_LEDGER_TABLES } from "./legacyLedgerSchema";
import { Pool, type PoolClient } from "pg";
import { LEDGER_INDEXES, LEDGER_TABLES, LEDGER_UNIQUE_KEYS } from "./ledgerSchema";
import { ledgerSnapshotFingerprint, validateLedgerSnapshot, type LedgerSnapshot, type LedgerRow } from "./LedgerStorageSnapshot";

const LOCK = "SELECT pg_advisory_xact_lock(730021, 3)";

/** Complete ledger migration target. Live billing routing is deliberately not switched here. */
export class PostgresLedgerStorage {
  private pool: Pool;
  constructor(url: string) {
    if (!url) throw new Error("Credit ledger storage requires a PostgreSQL URL");
    this.pool = new Pool({ connectionString:url, max:4, connectionTimeoutMillis:5000,
      statement_timeout:10000, lock_timeout:5000, idleTimeoutMillis:30000 });
  }

  private async transaction<T>(operation: (client:PoolClient) => Promise<T>): Promise<T> {
    const client = await this.pool.connect();
    let discard: Error | undefined;
    try {
      await client.query("BEGIN");
      await client.query(LOCK);
      const result = await operation(client);
      await client.query("COMMIT");
      return result;
    } catch (error) {
      try { await client.query("ROLLBACK"); } catch { discard = new Error("Credit ledger transaction connection failed"); }
      throw error;
    } finally { client.release(discard); }
  }

  async init(): Promise<void> {
    await this.transaction(async client => {
      await client.query("CREATE SCHEMA IF NOT EXISTS orvyn_billing");
      await client.query("CREATE TABLE IF NOT EXISTS orvyn_billing.migrations(version INTEGER PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())");
      const applied = await client.query("SELECT version FROM orvyn_billing.migrations ORDER BY version");
      if (applied.rows.some(row => row.version !== 1)) throw new Error("Unsupported ledger storage version");
      // Historical balances are preserved as an archive, never replayed as grants.
      await client.query("CREATE SCHEMA IF NOT EXISTS orvyn_billing_archive");
      for (const legacy of LEGACY_LEDGER_TABLES) await client.query(`CREATE TABLE IF NOT EXISTS orvyn_billing_archive."${legacy.name}" (${legacy.columns.map(c => `"${c.name}" ${c.type === "INTEGER" ? "BIGINT" : c.type === "REAL" ? "DOUBLE PRECISION" : "TEXT"} ${c.name === legacy.key ? "PRIMARY KEY" : "NOT NULL"}`).join(",")})`);
      if (applied.rowCount) return;
      for (const table of LEDGER_TABLES) {
        // SQL comes exclusively from the checked-in contract, never from imported files.
        await client.query(table.sql.replace(/CREATE TABLE(?: IF NOT EXISTS)?\s+\w+/i,
          `CREATE TABLE orvyn_billing."${table.name}"`).replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g,
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY").replace(/\bINTEGER\b/g, "BIGINT").replace(/\bREAL\b/g, "DOUBLE PRECISION"));
      }
      for (const sql of LEDGER_INDEXES) await client.query(sql.replace(/\bON\s+(\w+)/i, 'ON orvyn_billing."$1"'));
      await client.query("CREATE TABLE orvyn_billing.imports(fingerprint TEXT PRIMARY KEY, imported_at TIMESTAMPTZ NOT NULL DEFAULT now())");
      await client.query("CREATE TABLE orvyn_billing.source_sequences(name TEXT PRIMARY KEY,seq BIGINT NOT NULL)");
      await client.query(`CREATE FUNCTION orvyn_billing.reject_ledger_mutation() RETURNS trigger LANGUAGE plpgsql AS
        $$ BEGIN RAISE EXCEPTION 'ledger_entries is append-only'; END; $$;
        CREATE TRIGGER ledger_entries_append_only BEFORE UPDATE OR DELETE ON orvyn_billing.ledger_entries
        FOR EACH ROW EXECUTE FUNCTION orvyn_billing.reject_ledger_mutation();
        CREATE TRIGGER ledger_entries_no_truncate BEFORE TRUNCATE ON orvyn_billing.ledger_entries
        FOR EACH STATEMENT EXECUTE FUNCTION orvyn_billing.reject_ledger_mutation()`);
      await client.query("INSERT INTO orvyn_billing.migrations(version) VALUES (1)");
    });
  }

  private async read(client: PoolClient): Promise<LedgerSnapshot> {
    // Keep the cross-table view consistent even if an operator writes outside this repository.
    await client.query(`LOCK TABLE ${LEDGER_TABLES.map(table => `orvyn_billing."${table.name}"`).join(",")},orvyn_billing.source_sequences IN SHARE ROW EXCLUSIVE MODE`);
    const version = await client.query("SELECT version FROM orvyn_billing.migrations ORDER BY version");
    if (version.rows.length !== 1 || version.rows[0].version !== 1) throw new Error("Unsupported ledger storage version");
    const inventory = await client.query("SELECT table_name FROM information_schema.tables WHERE table_schema='orvyn_billing' ORDER BY table_name");
    const expected = [...LEDGER_TABLES.map(table => table.name), "imports", "migrations", "source_sequences"].sort();
    if (JSON.stringify(inventory.rows.map(row => row.table_name)) !== JSON.stringify(expected)) throw new Error("PostgreSQL ledger table inventory differs");
    const columns = await client.query("SELECT table_name,column_name,data_type,is_nullable FROM information_schema.columns WHERE table_schema='orvyn_billing'");
    const keys = await client.query(`SELECT c.relname AS table_name,array_agg(a.attname::text ORDER BY k.ord) AS columns
      FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace
      CROSS JOIN LATERAL unnest(con.conkey) WITH ORDINALITY k(attnum,ord)
      JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum=k.attnum
      WHERE n.nspname='orvyn_billing' AND con.contype IN ('p','u') GROUP BY c.relname,con.oid`);
    for (const table of LEDGER_TABLES) {
      const actual = columns.rows.filter(row => row.table_name === table.name);
      if (actual.length !== table.columns.length || table.columns.some(column => !actual.some(row =>
        row.column_name === column.name && row.data_type === (column.type === "INTEGER" ? "bigint" : column.type === "REAL" ? "double precision" : "text") &&
        row.is_nullable === (column.notNull || column.primaryKey ? "NO" : "YES")))) {
        throw new Error(`PostgreSQL ledger schema differs: ${table.name}`);
      }
      const canonical = (values: readonly (readonly string[])[]) => JSON.stringify(Array.from(new Set(values.map(value => JSON.stringify(value)))).sort());
      if (canonical(keys.rows.filter(row => row.table_name === table.name).map(row => row.columns)) !== canonical(LEDGER_UNIQUE_KEYS[table.name])) {
        throw new Error(`PostgreSQL ledger uniqueness differs: ${table.name}`);
      }
    }
    const bucket = await client.query("SELECT pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conrelid='orvyn_billing.ledger_entries'::regclass AND contype='c' AND convalidated");
    if (bucket.rows.length !== 1 || bucket.rows[0].definition.replace(/\s+/g," ") !== "CHECK ((bucket = ANY (ARRAY['included'::text, 'purchased'::text, 'hold'::text])))") throw new Error("PostgreSQL ledger bucket protection differs");
    const trigger = await client.query(`SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace
      WHERE n.nspname='orvyn_billing' AND c.relname='ledger_entries' AND t.tgname IN ('ledger_entries_append_only','ledger_entries_no_truncate') AND t.tgenabled='O'`);
    if (trigger.rowCount !== 2) throw new Error("PostgreSQL ledger ledger protections differ");
    const snapshot: LedgerSnapshot = {};
    for (const legacy of LEGACY_LEDGER_TABLES) {
      await client.query(`LOCK TABLE orvyn_billing_archive."${legacy.name}" IN SHARE ROW EXCLUSIVE MODE`);
      const columns = await client.query("SELECT column_name,data_type,is_nullable FROM information_schema.columns WHERE table_schema='orvyn_billing_archive' AND table_name=$1", [legacy.name]);
      if (columns.rows.length !== legacy.columns.length || legacy.columns.some(c => !columns.rows.some(row => row.column_name === c.name && row.data_type === (c.type === "INTEGER" ? "bigint" : c.type === "REAL" ? "double precision" : "text") && row.is_nullable === "NO"))) throw new Error("PostgreSQL archived ledger schema differs");
      const archive = await client.query(`SELECT * FROM orvyn_billing_archive."${legacy.name}"`);
      if (archive.rows.length) snapshot[`__legacy_${legacy.name}`] = archive.rows.map(row => Object.fromEntries(legacy.columns.map(c => [c.name, c.type === "TEXT" ? row[c.name] : Number(row[c.name])])));
    }
    for (const table of LEDGER_TABLES) {
      const result = await client.query(`SELECT * FROM orvyn_billing."${table.name}"`);
      snapshot[table.name] = result.rows.map(row => {
        const normalized: LedgerRow = {};
        for (const column of table.columns) normalized[column.name] = row[column.name] === null ? null :
          column.type === "INTEGER" || column.type === "REAL" ? Number(row[column.name]) : row[column.name];
        return normalized;
      });
    }
    const sequence = await client.query("SELECT last_value,is_called FROM orvyn_billing.ledger_entries_seq_seq");
    const recorded = await client.query("SELECT name,seq FROM orvyn_billing.source_sequences ORDER BY name");
    if (recorded.rows.some(row => row.name !== "ledger_entries")) throw new Error("Unsupported ledger sequence");
    const highWater = Number(sequence.rows[0].last_value) - (sequence.rows[0].is_called ? 0 : 1);
    snapshot.__sequences = highWater > 0 || recorded.rowCount ? [{ name:"ledger_entries", seq:highWater }] : [];
    validateLedgerSnapshot(snapshot);
    return snapshot;
  }

  async verify(snapshot: LedgerSnapshot): Promise<{ matches:boolean; fingerprint:string; counts:Record<string,number> }> {
    const fingerprint = ledgerSnapshotFingerprint(snapshot);
    return this.transaction(async client => {
      const stored = await this.read(client);
      return { matches:ledgerSnapshotFingerprint(stored) === fingerprint, fingerprint,
        counts:Object.fromEntries(LEDGER_TABLES.map(table => [table.name, stored[table.name].length])) };
    });
  }

  /** Private migration/restore tooling only: the returned records contain financial records. */
  async exportSnapshot(): Promise<LedgerSnapshot> { return this.transaction(client => this.read(client)); }

  /** Seed only an empty target; repeat of identical data is safe, differing data is never overwritten. */
  async importSnapshot(snapshot: LedgerSnapshot): Promise<{ imported:boolean; fingerprint:string }> {
    const fingerprint = ledgerSnapshotFingerprint(snapshot);
    return this.transaction(async client => {
      const current = await this.read(client);
      const imported = await client.query("SELECT 1 FROM orvyn_billing.imports LIMIT 1");
      const occupied = imported.rowCount || current.__sequences.length || LEGACY_LEDGER_TABLES.some(t => current[`__legacy_${t.name}`]?.length) || LEDGER_TABLES.some(table => current[table.name].length > 0);
      if (occupied) {
        if (ledgerSnapshotFingerprint(current) !== fingerprint) throw new Error("Credit ledger target differs; refusing to overwrite existing records");
        return { imported:false, fingerprint };
      }
      for (const table of LEDGER_TABLES) {
        const columns = table.columns.map(column => `"${column.name}"`).join(",");
        const placeholders = table.columns.map((_, index) => `$${index + 1}`).join(",");
        for (const row of snapshot[table.name]) await client.query(
          `INSERT INTO orvyn_billing."${table.name}"(${columns}) VALUES (${placeholders})`, table.columns.map(column => row[column.name]));
      }
      for (const row of snapshot.__sequences) {
        await client.query("INSERT INTO orvyn_billing.source_sequences(name,seq) VALUES ($1,$2)", [row.name,row.seq]);
      }
      for (const legacy of LEGACY_LEDGER_TABLES) for (const row of snapshot[`__legacy_${legacy.name}`] ?? []) await client.query(
        `INSERT INTO orvyn_billing_archive."${legacy.name}" (${legacy.columns.map(c => `"${c.name}"`).join(",")}) VALUES (${legacy.columns.map((_,i) => `$${i+1}`).join(",")})`, legacy.columns.map(c => row[c.name]));
      // RESTART is transactional, unlike setval/nextval: a failed import also restores
      // the counter. Explicit inserted ledger ids do not consume the identity sequence.
      const highWater = snapshot.__sequences.find(row => row.name === "ledger_entries")?.seq ?? 0;
      await client.query(`ALTER SEQUENCE orvyn_billing.ledger_entries_seq_seq RESTART WITH ${Number(highWater) + 1}`);
      if (ledgerSnapshotFingerprint(await this.read(client)) !== fingerprint) throw new Error("Credit ledger content verification failed");
      await client.query("INSERT INTO orvyn_billing.imports(fingerprint) VALUES ($1)", [fingerprint]);
      return { imported:true, fingerprint };
    });
  }

  async close(): Promise<void> { await this.pool.end(); }
}
