// Generated by scripts/generate-postgres-tenant.cjs from LocalStore.ts; do not edit.
import {PostgresTenantDatabase} from "./PostgresTenantDatabase";
import type {LocalStore} from "./LocalStore";
import type {TenantMirrorSnapshot} from "./TenantPostgresMirror";
type AsyncTenantContract={[K in keyof LocalStore]:LocalStore[K] extends (...args:infer A)=>infer R ? (...args:A)=>Promise<R>:LocalStore[K]};
import * as path from "path";
import * as fs from "fs";
import * as os from "os";
import type { ModelConfig } from "@orvyn/ai-core";
import type { Mission } from "../agent/TaskEngine";
import type { UsageEvent } from "../services/UsageService";
export function defaultDataDir(): string {
    const explicit = process.env.ORVYN_DATA_DIR?.trim();
    if (explicit)
        return explicit;
    // Each test process gets its own directory. Sharing ~/.orvyn/data/auth.db
    // across parallel test files is what produced SQLITE_BUSY.
    if (process.env.NODE_TEST_CONTEXT) {
        return path.join(os.tmpdir(), "orvyn-test-data", String(process.pid));
    }
    return path.join(os.homedir(), ".orvyn", "data");
}
/** One canonical preview record per run — a stale or foreign preview can never be resolved through it. */
export function previewEnvironmentKey(runId: string): string {
    return `pv_${runId}`;
}
export interface ArtifactRowInput {
    id: string;
    projectRoot?: string | null;
    runId?: string | null;
    chatId?: string | null;
    kind: string;
    name: string;
    path: string;
    mediaType?: string | null;
    sha256?: string | null;
    size?: number | null;
    sourceTool?: string | null;
    tenantId?: string | null;
    status?: string | null;
    previewable?: boolean;
    downloadable?: boolean;
    userId?: string | null;
    projectId?: string | null;
}
function mapArtifactRow(r: any) {
    return {
        id: String(r.id),
        projectRoot: r.project_root,
        runId: r.run_id,
        chatId: r.chat_id,
        kind: r.kind,
        name: r.name,
        path: r.path,
        mediaType: r.media_type,
        createdAt: Number(r.created_at),
        sha256: r.sha256,
        size: r.size != null ? Number(r.size) : undefined,
        sourceTool: r.source_tool,
        tenantId: r.tenant_id,
        status: r.status,
        updatedAt: r.updated_at != null ? Number(r.updated_at) : undefined,
        previewable: r.previewable,
        downloadable: r.downloadable,
        userId: r.user_id,
        projectId: r.project_id,
    };
}
export class PostgresTenantStore implements AsyncTenantContract {
    private constructor(private readonly db: PostgresTenantDatabase, readonly tenantId: string) { }
    static async connect(url: string, tenantId: string): Promise<PostgresTenantStore> {
        return new PostgresTenantStore(await PostgresTenantDatabase.connect(url, tenantId)
        //   - missions + tasks        (Mission Control history, resumable audit trail)
        //   - usage events            (billing basis — losing these loses money)
        //   - settings                (autonomy profile, per-project tool overrides)
        //   - user-added model configs
        //
        // Run event logs stay in-memory by design: they are a live stream, and the
        // durable outcome they produce (mission state, usage) is persisted here.
        // The cloud tier replaces this class with PostgreSQL behind the same calls.
        //
        // Every write is wrapped so a storage failure degrades to in-memory behavior
        // with a one-time warning instead of crashing an agent mid-mission.
        , //   - missions + tasks        (Mission Control history, resumable audit trail)
        //   - usage events            (billing basis — losing these loses money)
        //   - settings                (autonomy profile, per-project tool overrides)
        //   - user-added model configs
        //
        // Run event logs stay in-memory by design: they are a live stream, and the
        // durable outcome they produce (mission state, usage) is persisted here.
        // The cloud tier replaces this class with PostgreSQL behind the same calls.
        //
        // Every write is wrapped so a storage failure degrades to in-memory behavior
        // with a one-time warning instead of crashing an agent mid-mission.
        tenantId);
    }
    async close(): Promise<void> { await this.db.close(); }
    // ---------- missions ----------
    async saveMission(m: Mission): Promise<void> {
        return this.db.transaction(async () => {
            const saved = (await (async () => (await this.db
                .prepare(`INSERT INTO missions (id, run_id, project_root, goal, status, review_cycles, created_at, updated_at, tasks_json)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(id) DO UPDATE SET
             status = excluded.status,
             review_cycles = excluded.review_cycles,
             updated_at = excluded.updated_at,
             tasks_json = excluded.tasks_json`)
                .run(m.id, m.runId, m.projectRoot, m.goal, m.status, m.reviewCycles, m.createdAt, m.updatedAt, JSON.stringify(m.tasks))))());
        });
    }
    async loadMissions(limit = 200): Promise<Mission[]> {
        return this.db.transaction(async () => {
            return ((await (async () => {
                const rows = (await this.db
                    .prepare(`SELECT * FROM missions ORDER BY created_at DESC LIMIT ?`)
                    .all(limit)) as any[];
                return rows.map((r) => ({
                    id: String(r.id),
                    runId: String(r.run_id),
                    projectRoot: String(r.project_root),
                    goal: String(r.goal),
                    status: r.status,
                    reviewCycles: Number(r.review_cycles),
                    createdAt: Number(r.created_at),
                    updatedAt: Number(r.updated_at),
                    tasks: JSON.parse(String(r.tasks_json)),
                }));
            })()) ?? []);
        });
    }
    // ---------- usage ----------
    async saveUsageEvent(e: UsageEvent): Promise<void> {
        return this.db.transaction(async () => {
            const saved = (await (async () => (await this.db
                .prepare(`INSERT OR IGNORE INTO usage_events
           (id, ts, model_id, provider, method, duration_ms, ok, error, prompt_tokens, completion_tokens, output_chars, tool_calls, mission_id, task_id, agent, source)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
                .run(e.id, e.timestamp, e.modelId, e.provider, e.method, e.durationMs, e.ok ? 1 : 0, e.error ?? null, e.promptTokens ?? null, e.completionTokens ?? null, e.outputChars ?? null, e.toolCalls ?? null, e.missionId ?? null, e.taskId ?? null, e.agent ?? null, e.source ?? null)))());
        });
    }
    /** Count of model requests since `ts` — the basis for monthly quotas. */
    async countUsageSince(ts: number): Promise<number> {
        return this.db.transaction(async () => {
            return ((await (async () => {
                const row = (await this.db.prepare(`SELECT COUNT(*) AS n FROM usage_events WHERE ts >= ?`).get(ts)) as any;
                return Number(row?.n ?? 0);
            })()) ?? 0);
        });
    }
    /** Count of missions started since `ts` — the basis for monthly mission quotas. */
    async countMissionsSince(ts: number): Promise<number> {
        return this.db.transaction(async () => {
            return ((await (async () => {
                const row = (await this.db.prepare(`SELECT COUNT(*) AS n FROM missions WHERE created_at >= ?`).get(ts)) as any;
                return Number(row?.n ?? 0);
            })()) ?? 0);
        });
    }
    async loadRecentUsage(limit = 5000): Promise<UsageEvent[]> {
        return this.db.transaction(async () => {
            return ((await (async () => {
                const rows = (await this.db
                    .prepare(`SELECT * FROM usage_events ORDER BY ts DESC LIMIT ?`)
                    .all(limit)) as any[];
                return rows.reverse().map((r) => {
                    const e: UsageEvent = {
                        id: String(r.id),
                        timestamp: Number(r.ts),
                        modelId: String(r.model_id),
                        provider: String(r.provider),
                        method: r.method,
                        durationMs: Number(r.duration_ms),
                        ok: r.ok === 1,
                    };
                    if (r.error != null)
                        e.error = String(r.error);
                    if (r.prompt_tokens != null)
                        e.promptTokens = Number(r.prompt_tokens);
                    if (r.completion_tokens != null)
                        e.completionTokens = Number(r.completion_tokens);
                    if (r.output_chars != null)
                        e.outputChars = Number(r.output_chars);
                    if (r.tool_calls != null)
                        e.toolCalls = Number(r.tool_calls);
                    if (r.mission_id != null)
                        e.missionId = String(r.mission_id);
                    if (r.task_id != null)
                        e.taskId = String(r.task_id);
                    if (r.agent != null)
                        e.agent = String(r.agent);
                    if (r.source != null)
                        e.source = String(r.source);
                    return e;
                });
            })()) ?? []);
        });
    }
    // ---------- settings ----------
    async getSetting(key: string): Promise<string | null> {
        return this.db.transaction(async () => {
            return ((await (async () => {
                const row = (await this.db.prepare(`SELECT value FROM settings WHERE key = ?`).get(key)) as any;
                return row ? String(row.value) : null;
            })()) ?? null);
        });
    }
    async enqueueBilling(event: UsageEvent, own: boolean): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare("INSERT OR IGNORE INTO billing_outbox (id, event_json) VALUES (?, ?)").run(event.id, JSON.stringify({ event, own })));
        });
    }
    async pendingBilling(): Promise<Array<{
        event: UsageEvent;
        own: boolean;
    }>> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare("SELECT event_json FROM billing_outbox ORDER BY rowid LIMIT 1000").all()) as {
                event_json: string;
            }[]).map((row) => JSON.parse(row.event_json));
        });
    }
    async completeBilling(id: string): Promise<void> {
        return this.db.transaction(async () => { (await this.db.prepare("DELETE FROM billing_outbox WHERE id = ?").run(id)); });
    }
    async setSetting(key: string, value: string): Promise<void> {
        return this.db.transaction(async () => {
            const saved = (await (async () => (await this.db
                .prepare(`INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value`)
                .run(key, value)))());
        });
    }
    /** Per-project explicit tool permission overrides (the user's last word). */
    async getToolOverrides(projectRoot: string): Promise<Record<string, string>> {
        return this.db.transaction(async () => {
            const raw = (await this.getSetting(`toolOverrides:${projectRoot}`));
            if (!raw)
                return {};
            try {
                return JSON.parse(raw);
            }
            catch {
                return {};
            }
        });
    }
    async setToolOverride(projectRoot: string, tool: string, permission: string): Promise<void> {
        return this.db.transaction(async () => {
            const all = (await this.getToolOverrides(projectRoot));
            all[tool] = permission;
            (await this.setSetting(`toolOverrides:${projectRoot}`, JSON.stringify(all)));
        });
    }
    /** Approval grants remembered at the user's requested scope. */
    async getToolApprovalGrants(subjectId: string, sessionId: string, projectKey: string): Promise<string[]> {
        return this.db.transaction(async () => {
            const raw = (await this.getSetting(`toolApprovalGrants:${subjectId}`));
            if (!raw)
                return [];
            try {
                const data = JSON.parse(raw) as {
                    always?: string[];
                    sessions?: Record<string, string[]>;
                    projects?: Record<string, string[]>;
                };
                return [...new Set([...(data.always ?? []), ...(data.sessions?.[sessionId] ?? []), ...(data.projects?.[projectKey] ?? [])])];
            }
            catch {
                return [];
            }
        });
    }
    async saveToolApprovalGrant(scope: "session" | "project" | "always", subjectId: string, tool: string, sessionId: string, projectKey: string): Promise<void> {
        return this.db.transaction(async () => {
            const settingKey = `toolApprovalGrants:${subjectId}`;
            const raw = await this.getSetting(settingKey);
            let parsed: any;
            try {
                parsed = JSON.parse(raw ?? "{}");
            }
            catch {
                parsed = {};
            }
            const data = { always: parsed.always ?? [], sessions: parsed.sessions ?? {}, projects: parsed.projects ?? {} };
            const target = scope === "always" ? data.always : scope === "session" ? (data.sessions[sessionId] ??= []) : (data.projects[projectKey] ??= []);
            if (!target.includes(tool))
                target.push(tool);
            await this.setSetting(settingKey, JSON.stringify(data));
        });
    }
    async clearToolApprovalGrants(subjectId: string, tool: string): Promise<void> {
        return this.db.transaction(async () => {
            const settingKey = `toolApprovalGrants:${subjectId}`;
            const raw = await this.getSetting(settingKey);
            let parsed: any;
            try {
                parsed = JSON.parse(raw ?? "{}");
            }
            catch {
                return;
            }
            const strip = (list: unknown) => Array.isArray(list) ? list.filter(name => name !== tool) : [];
            const sessions = Object.fromEntries(Object.entries(parsed.sessions ?? {}).map(([id, list]) => [id, strip(list)]));
            const projects = Object.fromEntries(Object.entries(parsed.projects ?? {}).map(([id, list]) => [id, strip(list)]));
            await this.setSetting(settingKey, JSON.stringify({ always: strip(parsed.always), sessions, projects }));
        });
    }
    // ---------- ORION memory + artifact library ----------
    async saveMemory(input: {
        id: string;
        scope: "global" | "project";
        projectRoot?: string | null;
        kind: string;
        title: string;
        content: string;
        source?: string | null;
        pinned?: boolean;
    }): Promise<void> {
        return this.db.transaction(async () => {
            const now = Date.now();
            (await (async () => (await this.db.prepare(`INSERT INTO memories (id, scope, project_root, kind, title, content, source, pinned, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT(id) DO UPDATE SET scope=excluded.scope, project_root=excluded.project_root, kind=excluded.kind,
       title=excluded.title, content=excluded.content, source=excluded.source, pinned=excluded.pinned, updated_at=excluded.updated_at`).run(input.id, input.scope, input.projectRoot ?? null, input.kind, input.title, input.content, input.source ?? null, input.pinned ? 1 : 0, now, now)))());
        });
    }
    async listMemories(projectRoot?: string | null, limit = 200): Promise<any[]> {
        return this.db.transaction(async () => {
            return (await (async () => (await this.db.prepare(`SELECT * FROM memories WHERE scope='global' OR (scope='project' AND project_root = ?) ORDER BY pinned DESC, updated_at DESC LIMIT ?`).all(projectRoot ?? "", limit)).map((r: any) => ({
                id: String(r.id), scope: r.scope, projectRoot: r.project_root, kind: r.kind, title: r.title,
                content: r.content, source: r.source, pinned: r.pinned === 1, createdAt: Number(r.created_at), updatedAt: Number(r.updated_at)
            })))()) ?? [];
        });
    }
    async getMemory(id: string): Promise<any | null> {
        return this.db.transaction(async () => {
            return (await (async () => { const r: any = (await this.db.prepare(`SELECT * FROM memories WHERE id = ?`).get(id)); return r ? { id: String(r.id), scope: r.scope, projectRoot: r.project_root, kind: r.kind, title: r.title, content: r.content, source: r.source, pinned: r.pinned === 1, createdAt: Number(r.created_at), updatedAt: Number(r.updated_at) } : null; })()) ?? null;
        });
    }
    async deleteMemory(id: string): Promise<void> {
        return this.db.transaction(async () => {
            (await (async () => (await this.db.prepare(`DELETE FROM memories WHERE id = ?`).run(id)))());
        });
    }
    async saveArtifact(input: ArtifactRowInput): Promise<void> {
        return this.db.transaction(async () => {
            (await (async () => (await this.writeArtifactRow(input)))());
        });
    }
    /** Throws on storage failure — required for persist-before-ok. */
    async saveArtifactStrict(input: ArtifactRowInput): Promise<void> {
        return this.db.transaction(async () => {
            (await this.writeArtifactRow(input));
        });
    }
    private async writeArtifactRow(input: ArtifactRowInput): Promise<void> {
        return this.db.transaction(async () => {
            const now = Date.now();
            (await this.db.prepare(`INSERT INTO artifacts (id, project_root, run_id, kind, name, path, media_type, created_at, sha256, size, chat_id, source_tool, tenant_id, status, updated_at, previewable, downloadable, user_id, project_id)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT(id) DO UPDATE SET
         path=excluded.path, name=excluded.name, media_type=excluded.media_type,
         sha256=excluded.sha256, size=excluded.size, chat_id=excluded.chat_id,
         source_tool=excluded.source_tool, tenant_id=excluded.tenant_id, status=excluded.status,
         updated_at=excluded.updated_at, previewable=excluded.previewable, downloadable=excluded.downloadable,
         run_id=excluded.run_id, user_id=excluded.user_id, project_id=excluded.project_id`).run(input.id, input.projectRoot ?? null, input.runId ?? null, input.kind, input.name, input.path, input.mediaType ?? null, now, input.sha256 ?? null, input.size ?? null, input.chatId ?? null, input.sourceTool ?? null, input.tenantId ?? null, input.status ?? "ready", now, input.previewable === false ? 0 : 1, input.downloadable === false ? 0 : 1, input.userId ?? null, input.projectId ?? null));
        });
    }
    async listArtifacts(projectRoot?: string | null, limit = 200): Promise<any[]> {
        return this.db.transaction(async () => {
            return (await (async () => projectRoot
                ? (await this.db.prepare(`SELECT * FROM artifacts WHERE project_root = ? ORDER BY created_at DESC LIMIT ?`).all(projectRoot, limit)) : (await this.db.prepare(`SELECT * FROM artifacts ORDER BY created_at DESC LIMIT ?`).all(limit)))()) ?? [];
        });
    }
    async getArtifact(id: string): Promise<any | null> {
        return this.db.transaction(async () => {
            return (await (async () => {
                const r: any = (await this.db.prepare(`SELECT * FROM artifacts WHERE id = ?`).get(id));
                return r ? mapArtifactRow(r) : null;
            })()) ?? null;
        });
    }
    async deleteArtifact(id: string): Promise<void> {
        return this.db.transaction(async () => {
            (await (async () => (await this.db.prepare(`DELETE FROM artifacts WHERE id = ?`).run(id)))());
        });
    }
    async saveLearningRecord(input: {
        id: string;
        kind: string;
        payload: unknown;
    }): Promise<void> {
        return this.db.transaction(async () => {
            (await (async () => (await this.db.prepare(`INSERT INTO learning_records (id, kind, payload_json, created_at) VALUES (?, ?, ?, ?)
         ON CONFLICT(id) DO UPDATE SET payload_json=excluded.payload_json`).run(input.id, input.kind, JSON.stringify(input.payload), Date.now())))());
        });
    }
    async listLearningRecords(kind: string, limit = 80): Promise<{
        id: string;
        kind: string;
        payload: unknown;
        createdAt: number;
    }[]> {
        return this.db.transaction(async () => {
            return (await (async () => {
                const rows = (await this.db.prepare(`SELECT * FROM learning_records WHERE kind = ? ORDER BY created_at DESC LIMIT ?`).all(kind, limit)) as any[];
                return rows.map((r) => ({
                    id: String(r.id),
                    kind: String(r.kind),
                    payload: JSON.parse(String(r.payload_json)),
                    createdAt: Number(r.created_at),
                }));
            })()) ?? [];
        });
    }
    // ---------- mission checkpoints ----------
    /** One row per run; each meaningful step rewrites it. */
    async saveMissionCheckpoint(runId: string, checkpoint: unknown, phase?: string): Promise<void> {
        return this.db.transaction(async () => {
            (await (async () => (await this.db
                .prepare(`INSERT INTO mission_checkpoints (run_id, checkpoint_json, phase, updated_at)
           VALUES (?, ?, ?, ?)
           ON CONFLICT(run_id) DO UPDATE SET checkpoint_json=excluded.checkpoint_json, phase=excluded.phase, updated_at=excluded.updated_at`)
                .run(runId, JSON.stringify(checkpoint), phase ?? null, Date.now())))());
        });
    }
    async loadMissionCheckpoint(runId: string): Promise<unknown | null> {
        return this.db.transaction(async () => {
            return (await (async () => {
                const row: any = (await this.db.prepare(`SELECT checkpoint_json FROM mission_checkpoints WHERE run_id = ?`).get(runId));
                return row ? JSON.parse(String(row.checkpoint_json)) : null;
            })()) ?? null;
        });
    }
    async deleteMissionCheckpoint(runId: string): Promise<void> {
        return this.db.transaction(async () => {
            (await (async () => (await this.db.prepare(`DELETE FROM mission_checkpoints WHERE run_id = ?`).run(runId)))());
        });
    }
    // ---------- canonical preview environments ----------
    async savePreviewEnvironment(input: {
        id: string;
        organizationId?: string | null;
        projectId?: string | null;
        workspaceId?: string | null;
        runId: string;
        url: string;
        status: string;
    }): Promise<void> {
        return this.db.transaction(async () => {
            const now = Date.now();
            (await (async () => (await this.db
                .prepare(`INSERT INTO preview_environments (id, organization_id, project_id, workspace_id, run_id, url, status, created_at, updated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(id) DO UPDATE SET url=excluded.url, status=excluded.status, updated_at=excluded.updated_at`)
                .run(input.id, input.organizationId ?? null, input.projectId ?? null, input.workspaceId ?? null, input.runId, input.url, input.status, now, now)))());
        });
    }
    /** The preview record owned by THIS run/workspace — never another run's URL. */
    async previewEnvironmentFor(runId: string, workspaceId?: string | null): Promise<any | null> {
        return this.db.transaction(async () => {
            return (await (async () => {
                const row: any = workspaceId
                    ? (await this.db.prepare(`SELECT * FROM preview_environments WHERE run_id = ? AND workspace_id = ? ORDER BY updated_at DESC LIMIT 1`).get(runId, workspaceId)) : (await this.db.prepare(`SELECT * FROM preview_environments WHERE run_id = ? ORDER BY updated_at DESC LIMIT 1`).get(runId));
                if (!row)
                    return null;
                return {
                    id: String(row.id), organizationId: row.organization_id, projectId: row.project_id,
                    workspaceId: row.workspace_id, runId: String(row.run_id), url: String(row.url),
                    status: String(row.status), createdAt: Number(row.created_at), updatedAt: Number(row.updated_at),
                };
            })()) ?? null;
        });
    }
    async setPreviewEnvironmentStatus(id: string, status: string): Promise<void> {
        return this.db.transaction(async () => {
            (await (async () => (await this.db.prepare(`UPDATE preview_environments SET status = ?, updated_at = ? WHERE id = ?`).run(status, Date.now(), id)))());
        });
    }
    // ---------- content-addressed blobs ----------
    async saveBlobRow(input: {
        key: string;
        sha256: string;
        mediaType: string;
        size: number;
        path: string;
        organizationId?: string | null;
        projectId?: string | null;
        workspaceId?: string | null;
        runId?: string | null;
    }): Promise<void> {
        return this.db.transaction(async () => {
            (await (async () => (await this.db
                .prepare(`INSERT OR IGNORE INTO blobs (key, sha256, media_type, size, path, organization_id, project_id, workspace_id, run_id, created_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
                .run(input.key, input.sha256, input.mediaType, input.size, input.path, input.organizationId ?? null, input.projectId ?? null, input.workspaceId ?? null, input.runId ?? null, Date.now())))());
        });
    }
    async getBlobRow(key: string): Promise<any | null> {
        return this.db.transaction(async () => {
            return (await (async () => {
                const r: any = (await this.db.prepare(`SELECT * FROM blobs WHERE key = ?`).get(key));
                if (!r)
                    return null;
                return {
                    key: String(r.key), sha256: String(r.sha256), mediaType: String(r.media_type),
                    size: Number(r.size), path: String(r.path), organizationId: r.organization_id,
                    projectId: r.project_id, workspaceId: r.workspace_id, runId: r.run_id,
                    createdAt: Number(r.created_at),
                };
            })()) ?? null;
        });
    }
    // ---------- models ----------
    async saveModel(config: ModelConfig): Promise<void> {
        return this.db.transaction(async () => {
            const saved = (await (async () => (await this.db
                .prepare(`INSERT INTO models (id, config_json) VALUES (?, ?) ON CONFLICT(id) DO UPDATE SET config_json = excluded.config_json`)
                .run(config.id, JSON.stringify(config))))());
        });
    }
    async deleteModel(id: string): Promise<void> {
        return this.db.transaction(async () => {
            const saved = (await (async () => (await this.db.prepare(`DELETE FROM models WHERE id = ?`).run(id)))());
        });
    }
    async loadModels(): Promise<ModelConfig[]> {
        return this.db.transaction(async () => {
            return ((await (async () => {
                const rows = (await this.db.prepare(`SELECT config_json FROM models`).all()) as any[];
                return rows.map((r) => JSON.parse(String(r.config_json)) as ModelConfig);
            })()) ?? []);
        });
    }
    /** Full history for backfill, including rows outside the Reports window. */
    async tenantMirrorSnapshot(): Promise<TenantMirrorSnapshot> {
        return this.db.transaction(async () => {
            const snapshot: TenantMirrorSnapshot = {
                missions: (await this.loadMissions(2147483647)),
                usageEvents: (await this.loadRecentUsage(2147483647)),
                settings: (await this.db.prepare("SELECT key,value FROM settings ORDER BY key").all()) as unknown as Array<{
                    key: string;
                    value: string;
                }>,
                models: (await this.loadModels()),
            };
            // Guarded product reads return empty arrays on failure. Never interpret
            // that degraded result as an authoritative empty snapshot for deletion.
            const counts = (await this.tenantMirrorCounts());
            if (snapshot.missions.length !== counts.missions || snapshot.usageEvents.length !== counts.usage ||
                snapshot.models.length !== counts.models || snapshot.settings.length !== counts.settings) {
                throw new Error("Incomplete SQLite mirror snapshot");
            }
            return snapshot;
        });
    }
    async tenantMirrorCounts(): Promise<Record<string, number>> {
        return this.db.transaction(async () => {
            const count = async (table: string) => Number((await this.db.prepare(`SELECT COUNT(*) AS n FROM ${table}`).get()).n);
            return { missions: await count("missions"), usage: await count("usage_events"), settings: await count("settings"), models: await count("models") };
        });
    }
}
