// Generated by scripts/generate-postgres-sandboxes.cjs from SandboxRegistry.ts; do not edit.
import {PostgresSandboxDatabase} from "./PostgresSandboxDatabase";
import type {SandboxRegistry} from "./SandboxRegistry";
type AsyncSandboxContract={[K in keyof Omit<SandboxRegistry,"db">]:SandboxRegistry[K] extends (...args:infer A)=>infer R ? (...args:A)=>Promise<R>:SandboxRegistry[K]};
import { randomUUID } from "node:crypto";
import * as fs from "fs";
import * as path from "path";
export type SandboxProvider = "docker" | "openshell";
export type SandboxState = "provisioning" | "ready" | "running" | "degraded" | "recovering" | "completed" | "failed" | "stopping" | "stopped";
export const SANDBOX_STATES: SandboxState[] = ["provisioning", "ready", "running", "degraded", "recovering", "completed", "failed", "stopping", "stopped"];
export interface SandboxRecord {
    id: string;
    provider: SandboxProvider;
    providerSandboxId: string | null;
    organizationId: string;
    tenantId: string;
    userId: string;
    projectId: string | null;
    workspaceId: string;
    missionId: string | null;
    runId: string | null;
    state: SandboxState;
    policyTemplate: string;
    policyVersion: number;
    retention: "ephemeral" | "retained";
    workerId: string | null;
    fallbackReason: string | null;
    provisionMs: number | null;
    reconnects: number;
    execCount: number;
    execMs: number;
    policyDenials: number;
    lastError: string | null;
    createdAt: number;
    updatedAt: number;
    readyAt: number | null;
    destroyedAt: number | null;
    expiresAt: number | null;
}
export interface PolicyRequest {
    id: string;
    sandboxId: string | null;
    runId: string;
    organizationId: string;
    template: string;
    params: Record<string, string[]>;
    reason: string;
    status: "pending" | "approved" | "denied" | "applied" | "failed" | "expired";
    requestedBy: string;
    decidedBy: string | null;
    createdAt: number;
    decidedAt: number | null;
    appliedAt: number | null;
}
const IMMUTABLE: Array<keyof SandboxRecord> = ["provider", "organizationId", "tenantId", "userId", "projectId", "workspaceId", "runId", "createdAt"];
function snake(k: string): string { return k.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`); }
export class PostgresSandboxRegistry implements AsyncSandboxContract {
    private constructor(private readonly db: PostgresSandboxDatabase) { }
    static async connect(url: string): Promise<PostgresSandboxRegistry> {
        return new PostgresSandboxRegistry(await PostgresSandboxDatabase
            .
                connect(url));
    }
    async close(): Promise<void> { await this.db.close(); }
    private row(r: any): SandboxRecord | null {
        if (!r)
            return null;
        return {
            id: r.id, provider: r.provider, providerSandboxId: r.provider_sandbox_id, organizationId: r.organization_id,
            tenantId: r.tenant_id, userId: r.user_id, projectId: r.project_id, workspaceId: r.workspace_id,
            missionId: r.mission_id, runId: r.run_id, state: r.state, policyTemplate: r.policy_template,
            policyVersion: r.policy_version, retention: r.retention, workerId: r.worker_id, fallbackReason: r.fallback_reason,
            provisionMs: r.provision_ms, reconnects: r.reconnects, execCount: r.exec_count, execMs: r.exec_ms,
            policyDenials: r.policy_denials, lastError: r.last_error, createdAt: r.created_at, updatedAt: r.updated_at,
            readyAt: r.ready_at, destroyedAt: r.destroyed_at, expiresAt: r.expires_at,
        };
    }
    async plan(rec: Pick<SandboxRecord, "id" | "provider" | "organizationId" | "tenantId" | "userId" | "projectId" | "workspaceId" | "runId" | "policyTemplate" | "retention"> & {
        missionId?: string | null;
        fallbackReason?: string | null;
        expiresAt?: number | null;
    }, now = Date.now()): Promise<SandboxRecord> {
        return this.db.transaction(async () => {
            const existing = (await this.get(rec.id));
            if (existing) {
                for (const k of ["organizationId", "tenantId", "projectId", "workspaceId", "provider"] as const) {
                    if ((existing as any)[k] !== (rec as any)[k])
                        throw new Error(`sandbox ${rec.id}: ${k} is immutable`);
                }
                (await this.db.prepare(`UPDATE execution_sandboxes SET run_id = ?, state = 'provisioning', updated_at = ?, destroyed_at = NULL, expires_at = COALESCE(?, expires_at) WHERE id = ?`)
                    .run(rec.runId, now, rec.expiresAt ?? null, rec.id));
                return (await this.get(rec.id))!;
            }
            (await this.db.prepare(`INSERT INTO execution_sandboxes (id, provider, organization_id, tenant_id, user_id, project_id, workspace_id, mission_id, run_id, state, policy_template, policy_version, retention, fallback_reason, created_at, updated_at, expires_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'provisioning', ?, 1, ?, ?, ?, ?, ?)`)
                .run(rec.id, rec.provider, rec.organizationId, rec.tenantId, rec.userId, rec.projectId, rec.workspaceId, rec.missionId ?? null, rec.runId, rec.policyTemplate, rec.retention, rec.fallbackReason ?? null, now, now, rec.expiresAt ?? null));
            return (await this.get(rec.id))!;
        });
    }
    async get(id: string): Promise<SandboxRecord | null> {
        return this.db.transaction(async () => {
            return this.row((await this.db.prepare(`SELECT * FROM execution_sandboxes WHERE id = ?`).get(id)));
        });
    }
    async forRun(runId: string): Promise<SandboxRecord | null> {
        return this.db.transaction(async () => {
            return this.row((await this.db.prepare(`SELECT * FROM execution_sandboxes WHERE run_id = ? ORDER BY updated_at DESC LIMIT 1`).get(runId)));
        });
    }
    async report(id: string, patch: Partial<SandboxRecord>, now = Date.now()): Promise<SandboxRecord | null> {
        return this.db.transaction(async () => {
            const cur = (await this.get(id));
            if (!cur)
                return null;
            for (const k of IMMUTABLE) {
                if (patch[k] !== undefined && patch[k] !== cur[k])
                    return null;
            }
            const sets: string[] = [];
            const vals: any[] = [];
            const put = (k: keyof SandboxRecord, v: unknown) => { sets.push(`${snake(k)} = ?`); vals.push(v); };
            if (patch.state && SANDBOX_STATES.includes(patch.state)) {
                put("state", patch.state);
                if (patch.state === "ready" && !cur.readyAt)
                    put("readyAt", now);
            }
            if (patch.provider && patch.provider !== cur.provider)
                return null;
            if (patch.providerSandboxId !== undefined)
                put("providerSandboxId", patch.providerSandboxId);
            if (patch.workerId !== undefined)
                put("workerId", patch.workerId);
            if (patch.policyTemplate)
                put("policyTemplate", patch.policyTemplate);
            if (patch.policyVersion)
                put("policyVersion", patch.policyVersion);
            if (patch.provisionMs !== undefined)
                put("provisionMs", patch.provisionMs);
            if (patch.fallbackReason !== undefined)
                put("fallbackReason", patch.fallbackReason);
            if (patch.lastError !== undefined)
                put("lastError", patch.lastError ? String(patch.lastError).slice(0, 500) : null);
            if (patch.expiresAt !== undefined)
                put("expiresAt", patch.expiresAt);
            if (patch.destroyedAt !== undefined && !cur.destroyedAt)
                put("destroyedAt", patch.destroyedAt);
            put("updatedAt", now);
            vals.push(id);
            (await this.db.prepare(`UPDATE execution_sandboxes SET ${sets.join(", ")} WHERE id = ?`).run(...vals));
            return (await this.get(id));
        });
    }
    async recordFallback(id: string, to: SandboxProvider, reason: string, now = Date.now()): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`UPDATE execution_sandboxes SET provider = ?, fallback_reason = ?, updated_at = ? WHERE id = ?`).run(to, reason.slice(0, 300), now, id));
        });
    }
    async bump(id: string, field: "reconnects" | "policyDenials", n = 1): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`UPDATE execution_sandboxes SET ${snake(field)} = ${snake(field)} + ?, updated_at = ? WHERE id = ?`).run(n, Date.now(), id));
        });
    }
    async addExec(id: string, ms: number): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`UPDATE execution_sandboxes SET exec_count = exec_count + 1, exec_ms = exec_ms + ?, updated_at = ? WHERE id = ?`).run(Math.max(0, Math.round(ms)), Date.now(), id));
        });
    }
    async listForOrganization(organizationId: string, limit = 50): Promise<SandboxRecord[]> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare(`SELECT * FROM execution_sandboxes WHERE organization_id = ? ORDER BY created_at DESC LIMIT ?`).all(organizationId, limit)) as any[]).map((r) => this.row(r)!);
        });
    }
    async listForTenant(tenantId: string, limit = 50): Promise<SandboxRecord[]> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare(`SELECT * FROM execution_sandboxes WHERE tenant_id = ? ORDER BY created_at DESC LIMIT ?`).all(tenantId, limit)) as any[]).map((r) => this.row(r)!);
        });
    }
    async active(): Promise<SandboxRecord[]> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare(`SELECT * FROM execution_sandboxes WHERE state NOT IN ('completed','failed','stopped') ORDER BY created_at DESC`).all()) as any[]).map((r) => this.row(r)!);
        });
    }
    async authorizedSandbox(runId: string, templates: string[]): Promise<SandboxRecord | null> {
        return this.db.transaction(async () => {
            const rec = (await this.forRun(runId));
            if (!rec || rec.provider !== "openshell" || ["completed", "failed", "stopped"].includes(rec.state))
                return null;
            return (await this.policyRequests({ runId, limit: 50 })).some(r => (r.status === "approved" || r.status === "applied") && templates.includes(r.template)) ? rec : null;
        });
    }
    async failures(limit = 25): Promise<SandboxRecord[]> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare("SELECT * FROM execution_sandboxes WHERE state = 'failed' OR fallback_reason IS NOT NULL ORDER BY updated_at DESC LIMIT ?").all(limit)) as any[]).map(r => this.row(r)!);
        });
    }
    async stats(sinceMs: number, now = Date.now()): Promise<{
        byProvider: Record<string, {
            active: number;
            failed: number;
            created: number;
            avgProvisionMs: number | null;
            p95ProvisionMs: number | null;
            reconnects: number;
            policyDenials: number;
            execCount: number;
            execMs: number;
            fallbacks: number;
        }>;
    }> {
        return this.db.transaction(async () => {
            const out: Record<string, any> = {};
            for (const p of ["docker", "openshell"]) {
                const since = now - sinceMs;
                const q = async (sql: string, ...a: any[]) => (await this.db.prepare(sql).get(p, ...a)) as any;
                const active = (await q(`SELECT COUNT(*) n FROM execution_sandboxes WHERE provider = ? AND state NOT IN ('completed','failed','stopped')`)).n;
                const failed = (await q(`SELECT COUNT(*) n FROM execution_sandboxes WHERE provider = ? AND state = 'failed' AND updated_at >= ?`, since)).n;
                const agg = (await q(`SELECT COUNT(*) created, AVG(provision_ms) avg, SUM(reconnects) rc, SUM(policy_denials) pd, SUM(exec_count) ec, SUM(exec_ms) em, SUM(CASE WHEN fallback_reason IS NOT NULL THEN 1 ELSE 0 END) fb FROM execution_sandboxes WHERE provider = ? AND created_at >= ?`, since));
                const times = ((await this.db.prepare(`SELECT provision_ms v FROM execution_sandboxes WHERE provider = ? AND created_at >= ? AND provision_ms IS NOT NULL ORDER BY provision_ms`).all(p, since)) as any[]).map((r) => Number(r.v));
                out[p] = {
                    active, failed, created: agg.created ?? 0,
                    avgProvisionMs: agg.avg == null ? null : Math.round(agg.avg),
                    p95ProvisionMs: times.length ? times[Math.min(times.length - 1, Math.floor(times.length * 0.95))]! : null,
                    reconnects: agg.rc ?? 0, policyDenials: agg.pd ?? 0, execCount: agg.ec ?? 0, execMs: agg.em ?? 0, fallbacks: agg.fb ?? 0,
                };
            }
            return { byProvider: out };
        });
    }
    async staleCandidates(olderThanMs: number, now = Date.now()): Promise<SandboxRecord[]> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare(`SELECT * FROM execution_sandboxes WHERE state NOT IN ('completed','failed','stopped') AND updated_at < ?`).all(now - olderThanMs)) as any[]).map((r) => this.row(r)!);
        });
    }
    async setFlag(scope: "org" | "project", scopeId: string, flag: string, enabled: boolean, actor: string, now = Date.now()): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`INSERT INTO runtime_flags (scope, scope_id, flag, enabled, updated_by, updated_at) VALUES (?, ?, ?, ?, ?, ?)
      ON CONFLICT(scope, scope_id, flag) DO UPDATE SET enabled = excluded.enabled, updated_by = excluded.updated_by, updated_at = excluded.updated_at`)
                .run(scope, scopeId, flag, enabled ? 1 : 0, actor, now));
        });
    }
    async flag(scope: "org" | "project", scopeId: string, flag: string): Promise<boolean | null> {
        return this.db.transaction(async () => {
            const r = (await this.db.prepare(`SELECT enabled FROM runtime_flags WHERE scope = ? AND scope_id = ? AND flag = ?`).get(scope, scopeId, flag)) as any;
            return r ? Boolean(r.enabled) : null;
        });
    }
    async flags(flag: string): Promise<Array<{
        scope: string;
        scopeId: string;
        enabled: boolean;
        updatedBy: string;
        updatedAt: number;
    }>> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare(`SELECT * FROM runtime_flags WHERE flag = ? ORDER BY updated_at DESC`).all(flag)) as any[])
                .map((r) => ({ scope: r.scope, scopeId: r.scope_id, enabled: Boolean(r.enabled), updatedBy: r.updated_by, updatedAt: r.updated_at }));
        });
    }
    async audit(type: string, actor: string, opts: {
        sandboxId?: string | null;
        organizationId?: string | null;
        detail?: Record<string, unknown>;
    } = {}, now = Date.now()): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`INSERT INTO sandbox_audit (id, sandbox_id, organization_id, type, actor, detail, at) VALUES (?, ?, ?, ?, ?, ?, ?)`)
                .run(randomUUID(), opts.sandboxId ?? null, opts.organizationId ?? null, type, actor.slice(0, 120), JSON.stringify(opts.detail ?? {}).slice(0, 4000), now));
        });
    }
    async auditLog(opts: {
        organizationId?: string;
        sandboxId?: string;
        type?: string;
        limit?: number;
    } = {}): Promise<Array<{
        id: string;
        sandboxId: string | null;
        organizationId: string | null;
        type: string;
        actor: string;
        detail: Record<string, unknown>;
        at: number;
    }>> {
        return this.db.transaction(async () => {
            const where: string[] = [];
            const args: any[] = [];
            if (opts.organizationId) {
                where.push("organization_id = ?");
                args.push(opts.organizationId);
            }
            if (opts.sandboxId) {
                where.push("sandbox_id = ?");
                args.push(opts.sandboxId);
            }
            if (opts.type) {
                where.push("type = ?");
                args.push(opts.type);
            }
            args.push(Math.min(500, opts.limit ?? 100));
            return ((await this.db.prepare(`SELECT * FROM sandbox_audit ${where.length ? `WHERE ${where.join(" AND ")}` : ""} ORDER BY at DESC LIMIT ?`).all(...args)) as any[])
                .map((r) => ({ id: r.id, sandboxId: r.sandbox_id, organizationId: r.organization_id, type: r.type, actor: r.actor, detail: JSON.parse(r.detail || "{}"), at: r.at }));
        });
    }
    async countAudit(type: string, sinceMs: number, now = Date.now()): Promise<number> {
        return this.db.transaction(async () => {
            return ((await this.db.prepare(`SELECT COUNT(*) n FROM sandbox_audit WHERE type = ? AND at >= ?`).get(type, now - sinceMs)) as any).n;
        });
    }
    async requestPolicy(input: {
        sandboxId: string | null;
        runId: string;
        organizationId: string;
        template: string;
        params?: Record<string, string[]>;
        reason?: string;
        requestedBy: string;
    }, now = Date.now()): Promise<PolicyRequest> {
        return this.db.transaction(async () => {
            const dup = (await this.db.prepare(`SELECT id FROM sandbox_policy_requests WHERE run_id = ? AND template = ? AND params = ? AND status = 'pending'`)
                .get(input.runId, input.template, JSON.stringify(input.params ?? {}))) as any;
            if (dup)
                return (await this.policyRequest(dup.id))!;
            const id = `spr_${randomUUID().replace(/-/g, "").slice(0, 20)}`;
            (await this.db.prepare(`INSERT INTO sandbox_policy_requests (id, sandbox_id, run_id, organization_id, template, params, reason, status, requested_by, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)`)
                .run(id, input.sandboxId, input.runId, input.organizationId, input.template, JSON.stringify(input.params ?? {}), String(input.reason ?? "").slice(0, 500), input.requestedBy, now));
            return (await this.policyRequest(id))!;
        });
    }
    async policyRequest(id: string): Promise<PolicyRequest | null> {
        return this.db.transaction(async () => {
            const r = (await this.db.prepare(`SELECT * FROM sandbox_policy_requests WHERE id = ?`).get(id)) as any;
            if (!r)
                return null;
            return {
                id: r.id, sandboxId: r.sandbox_id, runId: r.run_id, organizationId: r.organization_id, template: r.template,
                params: JSON.parse(r.params || "{}"), reason: r.reason, status: r.status, requestedBy: r.requested_by,
                decidedBy: r.decided_by, createdAt: r.created_at, decidedAt: r.decided_at, appliedAt: r.applied_at,
            };
        });
    }
    async policyRequests(opts: {
        organizationId?: string;
        status?: string;
        runId?: string;
        limit?: number;
    } = {}): Promise<PolicyRequest[]> {
        return this.db.transaction(async () => {
            const where: string[] = [];
            const args: any[] = [];
            if (opts.organizationId) {
                where.push("organization_id = ?");
                args.push(opts.organizationId);
            }
            if (opts.status) {
                where.push("status = ?");
                args.push(opts.status);
            }
            if (opts.runId) {
                where.push("run_id = ?");
                args.push(opts.runId);
            }
            args.push(Math.min(200, opts.limit ?? 50));
            return Promise.all(((await this.db.prepare(`SELECT id FROM sandbox_policy_requests ${where.length ? `WHERE ${where.join(" AND ")}` : ""} ORDER BY created_at DESC LIMIT ?`).all(...args)) as any[]).map(async (r) => (await this.policyRequest(r.id))!));
        });
    }
    async decidePolicy(id: string, approve: boolean, actor: string, now = Date.now()): Promise<PolicyRequest | null> {
        return this.db.transaction(async () => {
            const cur = (await this.policyRequest(id));
            if (!cur || cur.status !== "pending")
                return cur;
            if (actor === cur.requestedBy || /^(model|agent|run):/.test(actor))
                throw new Error("A policy request can only be decided by a person.");
            (await this.db.prepare(`UPDATE sandbox_policy_requests SET status = ?, decided_by = ?, decided_at = ? WHERE id = ?`).run(approve ? "approved" : "denied", actor, now, id));
            return (await this.policyRequest(id));
        });
    }
    async markPolicyApplied(id: string, ok: boolean, now = Date.now()): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`UPDATE sandbox_policy_requests SET status = ?, applied_at = ? WHERE id = ? AND status = 'approved'`).run(ok ? "applied" : "failed", now, id));
        });
    }
    async nextApproved(runId: string): Promise<PolicyRequest | null> {
        return this.db.transaction(async () => {
            const r = (await this.db.prepare(`SELECT id FROM sandbox_policy_requests WHERE run_id = ? AND status = 'approved' ORDER BY decided_at ASC LIMIT 1`).get(runId)) as any;
            return r ? (await this.policyRequest(r.id)) : null;
        });
    }
    async expireRequests(runId: string): Promise<void> {
        return this.db.transaction(async () => {
            (await this.db.prepare(`UPDATE sandbox_policy_requests SET status = 'expired' WHERE run_id = ? AND status IN ('pending','approved')`).run(runId));
        });
    }
}
