// Generated by scripts/generate-postgres-sessions.cjs from WorkSessionStore.ts; do not edit.
import {PostgresSessionDatabase} from "./PostgresSessionDatabase";
import type {WorkSessionStore} from "./WorkSessionStore";
type AsyncSessionContract={[K in keyof WorkSessionStore]:WorkSessionStore[K] extends (...args:infer A)=>infer R ? (...args:A)=>Promise<R>:WorkSessionStore[K]};
import { randomBytes } from "crypto";
import * as fs from "fs";
import * as path from "path";
import { defaultDataDir } from "../persistence/LocalStore";
import { computeWorkspaceFingerprint, type WorkspaceFingerprint } from "./workspaceFingerprint";
export type WorkSessionStatus = "active" | "idle" | "archived";
export type SessionMessageRole = "user" | "assistant" | "system";
/** One message of a conversation, stored the moment it is sent. */
export interface SessionMessage {
    messageId: string;
    sessionId: string;
    role: SessionMessageRole;
    content: string;
    /** The run this message started or answered, if any. */
    runId: string | null;
    /** Position in the session: 1, 2, 3 … assigned by the backend, never reused. */
    sequence: number;
    /** "chat", "agent", "research" … as the composer sent it. */
    mode: string | null;
    /** "complete", or "streaming" while an assistant reply is still arriving. */
    status: "complete" | "streaming";
    /** Extra detail kept with the message (e.g. the web research activity of a reply). */
    meta?: Record<string, unknown>;
    createdAt: number;
    updatedAt: number;
}
export interface WorkSession {
    sessionId: string;
    tenantId: string;
    userId: string;
    title: string;
    projectId: string | null;
    workspaceId: string | null;
    projectRoot: string | null;
    runIds: string[];
    activeRunId: string | null;
    status: WorkSessionStatus;
    pinned: boolean;
    createdAt: number;
    updatedAt: number;
}
const MAX_MESSAGE = 200000;
interface MessageRow {
    message_id: string;
    session_id: string;
    role: string;
    content: string;
    run_id: string | null;
    sequence: number;
    mode: string | null;
    status: string;
    created_at: number;
    updated_at: number;
    meta_json?: string | null;
}
function messageFromRow(r: MessageRow): SessionMessage {
    return {
        messageId: r.message_id,
        sessionId: r.session_id,
        role: (["user", "assistant", "system"].includes(r.role) ? r.role : "user") as SessionMessageRole,
        content: r.content,
        runId: r.run_id,
        sequence: r.sequence,
        mode: r.mode,
        status: r.status === "streaming" ? "streaming" : "complete",
        meta: (() => { try {
            return r.meta_json ? JSON.parse(r.meta_json) : undefined;
        }
        catch {
            return undefined;
        } })(),
        createdAt: r.created_at,
        updatedAt: r.updated_at,
    };
}
const id = (prefix: string) => `${prefix}_${randomBytes(8).toString("hex")}`;
/** Same folder, same key: case and slashes do not make a new workspace. */
export function rootKey(projectRoot: string): string {
    const r = projectRoot.trim().replace(/\\/g, "/").replace(/\/+$/, "");
    return /^[A-Za-z]:\//.test(r) || r.startsWith("//") ? r.toLowerCase() : r;
}
/** Relative project path stored on a workspace. Rejects escapes. */
export function normalizeKnownFile(filePath: string): string {
    const rel = String(filePath ?? "").trim().replace(/\\/g, "/").replace(/^\.\//, "").replace(/^\/+/, "");
    if (!rel || rel === "." || rel.split("/").includes(".."))
        return "";
    return rel;
}
function parseKnownFiles(raw: string | null | undefined): string[] {
    if (!raw)
        return [];
    try {
        const parsed = JSON.parse(raw);
        if (!Array.isArray(parsed))
            return [];
        const out: string[] = [];
        for (const item of parsed) {
            if (typeof item !== "string")
                continue;
            const rel = normalizeKnownFile(item);
            if (rel && !out.includes(rel))
                out.push(rel);
        }
        return out;
    }
    catch {
        return [];
    }
}
interface Row {
    session_id: string;
    tenant_id: string;
    user_id: string;
    title: string;
    project_id: string | null;
    workspace_id: string | null;
    project_root: string | null;
    run_ids_json: string;
    active_run_id: string | null;
    status: string;
    pinned: number;
    created_at: number;
    updated_at: number;
}
function fromRow(r: Row): WorkSession {
    let runIds: string[] = [];
    try {
        runIds = JSON.parse(r.run_ids_json);
    }
    catch { /* corrupt → empty */ }
    return {
        sessionId: r.session_id,
        tenantId: r.tenant_id,
        userId: r.user_id,
        title: r.title,
        projectId: r.project_id,
        workspaceId: r.workspace_id,
        projectRoot: r.project_root,
        runIds,
        activeRunId: r.active_run_id,
        status: (r.status as WorkSessionStatus) || "active",
        pinned: r.pinned === 1,
        createdAt: r.created_at,
        updatedAt: r.updated_at,
    };
}
export interface WorkspaceRecord {
    workspaceId: string;
    projectId: string;
    /** Stable id for this project tree. Physical mount paths can change. */
    logicalWorkspaceId: string;
    projectRoot: string;
    knownFiles: string[];
    storageType: string;
    status: string;
    branch?: string;
    gitHead?: string;
    fingerprint?: WorkspaceFingerprint;
}
export type { WorkspaceFingerprint };
export class PostgresWorkSessionStore implements AsyncSessionContract {
    private constructor(private readonly db: PostgresSessionDatabase, private readonly tenantId: string, readonly dataDirectory: string) { }
    static async connect(url: string, tenantId: string, dataDirectory: string = defaultDataDir()): Promise<PostgresWorkSessionStore> {
        return new PostgresWorkSessionStore(await PostgresSessionDatabase.connect(url, tenantId), tenantId, dataDirectory);
    }
    async close(): Promise<void // one file per tenant, so closing the app or redeploying the backend changes
    // nothing about a session.
    //
    // Workspaces get stable ids too: the same folder always maps to the same
    // workspaceId/projectId, so a session can be reattached even if its path is
    // later shown differently.
    > { await this.db.close(); }
    /** The stable workspace (and project) for a folder; created the first time it is seen. */
    async workspaceFor(projectRoot: string): Promise<{
        workspaceId: string;
        projectId: string;
        created: boolean;
    }> {
        return this.db.transaction(async () => {
            const key = rootKey(projectRoot);
            const hit = (await this.db.prepare(`SELECT workspace_id, project_id FROM workspaces WHERE root_key = ?`).get(key)) as {
                workspace_id: string;
                project_id: string;
            } | undefined;
            if (hit)
                return { workspaceId: hit.workspace_id, projectId: hit.project_id, created: false };
            const w = { workspaceId: id("ws"), projectId: id("proj"), created: true };
            const now = Date.now();
            (await this.db.prepare(`INSERT INTO workspaces (workspace_id, project_id, root_key, project_root, created_at, known_files_json, logical_workspace_id, storage_type, status, updated_at) VALUES (?, ?, ?, ?, ?, '[]', ?, 'local', 'ready', ?)`)
                .run(w.workspaceId, w.projectId, key, projectRoot, now, w.workspaceId, now));
            return w;
        });
    }
    /**
     * A new per-chat workspace directory under the tenant data dir:
     * `<ORVYN_DATA_DIR>/tenants/<tenantId>/workspaces/<workspaceId>`.
     * On ORVYN Cloud that data dir is a persistent volume. This directory is
     * the canonical project. A worker sandbox may copy it and must copy
     * changes back; the sandbox is not the stored project.
     */
    async provisionWorkspace(): Promise<{
        workspaceId: string;
        projectId: string;
        projectRoot: string;
    }> {
        return this.db.transaction(async () => {
            const workspaceId = id("ws");
            const projectId = id("proj");
            const dir = path.join(this.dataDirectory, "tenants", this.tenantId, "workspaces", workspaceId);
            fs.mkdirSync(dir, { recursive: true });
            const projectRoot = fs.realpathSync(dir);
            const now = Date.now();
            (await this.db.prepare(`INSERT INTO workspaces (workspace_id, project_id, root_key, project_root, created_at, known_files_json, logical_workspace_id, storage_type, status, updated_at) VALUES (?, ?, ?, ?, ?, '[]', ?, 'managed', 'ready', ?)`)
                .run(workspaceId, projectId, rootKey(projectRoot), projectRoot, now, workspaceId, now));
            return { workspaceId, projectId, projectRoot };
        });
    }
    async getWorkspace(workspaceId: string): Promise<WorkspaceRecord | undefined> {
        return this.db.transaction(async () => {
            const row = (await this.db.prepare(`SELECT workspace_id, project_id, project_root, known_files_json, logical_workspace_id, storage_type, status, branch, git_head, fingerprint_json FROM workspaces WHERE workspace_id = ?`).get(workspaceId)) as {
                workspace_id: string;
                project_id: string;
                project_root: string;
                known_files_json?: string | null;
                logical_workspace_id?: string | null;
                storage_type?: string | null;
                status?: string | null;
                branch?: string | null;
                git_head?: string | null;
                fingerprint_json?: string | null;
            } | undefined;
            if (!row)
                return undefined;
            let fingerprint: WorkspaceFingerprint | undefined;
            try {
                fingerprint = row.fingerprint_json ? JSON.parse(row.fingerprint_json) as WorkspaceFingerprint : undefined;
            }
            catch {
                fingerprint = undefined;
            }
            return {
                workspaceId: row.workspace_id,
                projectId: row.project_id,
                logicalWorkspaceId: row.logical_workspace_id || row.workspace_id,
                projectRoot: row.project_root,
                knownFiles: parseKnownFiles(row.known_files_json),
                storageType: row.storage_type || "managed",
                status: row.status || "ready",
                branch: row.branch || undefined,
                gitHead: row.git_head || undefined,
                fingerprint,
            };
        });
    }
    /** Point the same logical workspace at a directory that actually has the project. */
    async relocateWorkspace(workspaceId: string, projectRoot: string): Promise<boolean> {
        return this.db.transaction(async () => {
            const current = (await this.getWorkspace(workspaceId));
            if (!current)
                return false;
            if (!fs.existsSync(projectRoot) || !fs.statSync(projectRoot).isDirectory())
                return false;
            const real = fs.realpathSync(projectRoot);
            const key = rootKey(real);
            const other = (await this.db.prepare(`SELECT workspace_id FROM workspaces WHERE root_key = ? AND workspace_id != ?`).get(key, workspaceId)) as {
                workspace_id: string;
            } | undefined;
            if (other)
                return false;
            (await this.db.prepare(`UPDATE workspaces SET project_root = ?, root_key = ?, updated_at = ?, status = 'ready', last_opened_at = ? WHERE workspace_id = ?`)
                .run(real, key, Date.now(), Date.now(), workspaceId));
            return true;
        });
    }
    async persistFingerprint(workspaceId: string): Promise<WorkspaceFingerprint | undefined> {
        return this.db.transaction(async () => {
            const current = (await this.getWorkspace(workspaceId));
            if (!current)
                return undefined;
            const fingerprint = computeWorkspaceFingerprint(current.projectId, current.logicalWorkspaceId, current.projectRoot, {
                branch: current.branch,
                head: current.gitHead,
            });
            (await this.db.prepare(`UPDATE workspaces SET fingerprint_json = ?, updated_at = ? WHERE workspace_id = ?`)
                .run(JSON.stringify(fingerprint), Date.now(), workspaceId));
            return fingerprint;
        });
    }
    async knownFiles(workspaceId: string): Promise<string[]> {
        return this.db.transaction(async () => {
            return (await this.getWorkspace(workspaceId))?.knownFiles ?? [];
        });
    }
    /** Remember project files that have existed in this workspace. Paths are relative. */
    async rememberFiles(workspaceId: string, files: string[]): Promise<string[]> {
        return this.db.transaction(async () => {
            const current = (await this.knownFiles(workspaceId));
            const next = current.slice();
            for (const file of files) {
                const rel = normalizeKnownFile(file);
                if (!rel || next.includes(rel))
                    continue;
                next.push(rel);
            }
            (await this.db.prepare(`UPDATE workspaces SET known_files_json = ?, updated_at = ? WHERE workspace_id = ?`).run(JSON.stringify(next), Date.now(), workspaceId));
            (await this.persistFingerprint(workspaceId));
            return next;
        });
    }
    /** Point a session at a workspace. Does not mint a new id when one is already stored. */
    async bindWorkspace(sessionId: string, binding: {
        workspaceId: string;
        projectId: string;
        projectRoot: string;
    }): Promise<WorkSession | undefined> {
        return this.db.transaction(async () => {
            if (!(await this.get(sessionId)))
                return undefined;
            (await this.db.prepare(`UPDATE work_sessions SET workspace_id = ?, project_id = ?, project_root = ?, updated_at = ? WHERE session_id = ?`)
                .run(binding.workspaceId, binding.projectId, binding.projectRoot, Date.now(), sessionId));
            return (await this.get(sessionId));
        });
    }
    async create(input: {
        title: string;
        userId?: string;
        projectRoot?: string | null;
        projectId?: string | null;
    }): Promise<WorkSession> {
        return this.db.transaction(async () => {
            const now = Date.now();
            const root = input.projectRoot?.trim() || null;
            const ws = root ? (await this.workspaceFor(root)) : null;
            const session: WorkSession = {
                sessionId: id("sess"),
                tenantId: this.tenantId,
                userId: input.userId ?? "",
                title: (input.title || "New conversation").slice(0, 120),
                // A Cloud project (the account's project list) or the workspace's own id.
                projectId: input.projectId ?? ws?.projectId ?? null,
                workspaceId: ws?.workspaceId ?? null,
                projectRoot: root,
                runIds: [],
                activeRunId: null,
                status: "active",
                pinned: false,
                createdAt: now,
                updatedAt: now,
            };
            (await this.db.prepare(`INSERT INTO work_sessions (session_id, tenant_id, user_id, title, project_id, workspace_id, project_root, run_ids_json, active_run_id, status, pinned, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, '[]', NULL, 'active', 0, ?, ?)`).run(session.sessionId, this.tenantId, session.userId, session.title, session.projectId, session.workspaceId, session.projectRoot, now, now));
            return session;
        });
    }
    async get(sessionId: string): Promise<WorkSession | undefined> {
        return this.db.transaction(async () => {
            const r = (await this.db.prepare(`SELECT * FROM work_sessions WHERE session_id = ? AND tenant_id = ?`).get(sessionId, this.tenantId)) as Row | undefined;
            return r ? fromRow(r) : undefined;
        });
    }
    async list(limit = 200): Promise<WorkSession[]> {
        return this.db.transaction(async () => {
            const rows = (await this.db.prepare(`SELECT * FROM work_sessions WHERE tenant_id = ? ORDER BY updated_at DESC LIMIT ?`).all(this.tenantId, limit)) as unknown as Row[];
            return rows.map(fromRow);
        });
    }
    async sessionOfRun(runId: string): Promise<WorkSession | undefined> {
        return this.db.transaction(async () => {
            const r = (await this.db.prepare(`SELECT session_id FROM session_runs WHERE run_id = ?`).get(runId)) as {
                session_id: string;
            } | undefined;
            return r ? (await this.get(r.session_id)) : undefined;
        });
    }
    /** A run joins the session; it becomes the session's active run. */
    async attachRun(sessionId: string, runId: string, projectRoot?: string | null): Promise<WorkSession | undefined> {
        return this.db.transaction(async () => {
            const s = (await this.get(sessionId));
            if (!s)
                return undefined;
            const runIds = s.runIds.includes(runId) ? s.runIds : [...s.runIds, runId];
            let { workspaceId, projectId } = s;
            let root = s.projectRoot;
            if (!workspaceId && projectRoot?.trim()) {
                const ws = (await this.workspaceFor(projectRoot));
                workspaceId = ws.workspaceId;
                projectId = ws.projectId;
                root = projectRoot.trim();
            }
            const now = Date.now();
            (await this.db.prepare(`UPDATE work_sessions SET run_ids_json = ?, active_run_id = ?, workspace_id = ?, project_id = ?, project_root = ?, status = CASE WHEN status = 'archived' THEN status ELSE 'active' END, updated_at = ? WHERE session_id = ?`).run(JSON.stringify(runIds), runId, workspaceId, projectId, root, now, sessionId));
            (await this.db.prepare(`INSERT OR REPLACE INTO session_runs (run_id, session_id) VALUES (?, ?)`).run(runId, sessionId));
            return (await this.get(sessionId));
        });
    }
    async update(sessionId: string, patch: {
        title?: string;
        status?: WorkSessionStatus;
        pinned?: boolean;
    }): Promise<WorkSession | undefined> {
        return this.db.transaction(async () => {
            const s = (await this.get(sessionId));
            if (!s)
                return undefined;
            const title = patch.title !== undefined ? String(patch.title).slice(0, 120) || s.title : s.title;
            const status = patch.status && ["active", "idle", "archived"].includes(patch.status) ? patch.status : s.status;
            const pinned = patch.pinned !== undefined ? patch.pinned : s.pinned;
            (await this.db.prepare(`UPDATE work_sessions SET title = ?, status = ?, pinned = ?, updated_at = ? WHERE session_id = ?`)
                .run(title, status, pinned ? 1 : 0, Date.now(), sessionId));
            return (await this.get(sessionId));
        });
    }
    /** Moves a conversation into a project (or out of one: null). */
    async setProject(sessionId: string, projectId: string | null): Promise<WorkSession | undefined> {
        return this.db.transaction(async () => {
            if (!(await this.get(sessionId)))
                return undefined;
            (await this.db.prepare(`UPDATE work_sessions SET project_id = ?, updated_at = ? WHERE session_id = ?`).run(projectId, Date.now(), sessionId));
            return (await this.get(sessionId));
        });
    }
    async delete(sessionId: string): Promise<boolean> {
        return this.db.transaction(async () => {
            const r = (await this.db.prepare(`DELETE FROM work_sessions WHERE session_id = ? AND tenant_id = ?`).run(sessionId, this.tenantId));
            (await this.db.prepare(`DELETE FROM session_runs WHERE session_id = ?`).run(sessionId));
            (await this.db.prepare(`DELETE FROM session_messages WHERE session_id = ?`).run(sessionId));
            return Number(r.changes) > 0;
        });
    }
    // ── Messages ────────────────────────────────────────────────────────────
    /**
     * Stores one message now (not on a timer). Idempotent by messageId: sending
     * the same id again updates that message instead of adding a second one,
     * so a client can retry safely. The sequence is assigned here, once.
     */
    async appendMessage(sessionId: string, input: {
        messageId?: string;
        role: SessionMessageRole;
        content: string;
        runId?: string | null;
        mode?: string | null;
        status?: "complete" | "streaming";
        createdAt?: number;
        meta?: Record<string, unknown>;
    }): Promise<SessionMessage | undefined> {
        return this.db.transaction(async () => {
            if (!(await this.get(sessionId)))
                return undefined;
            const content = String(input.content ?? "").slice(0, MAX_MESSAGE);
            const messageId = input.messageId?.trim() || id("msg");
            const existing = (await this.getMessage(messageId));
            if (existing) {
                if (existing.sessionId !== sessionId)
                    return undefined;
                return (await this.updateMessage(messageId, { content, runId: input.runId ?? existing.runId, status: input.status ?? existing.status }));
            }
            const now = Date.now();
            const createdAt = Number.isFinite(input.createdAt) ? Number(input.createdAt) : now;
            // Next position in this session. One statement, so two writers never share a sequence.
            (await this.db.prepare(`INSERT INTO session_messages (message_id, session_id, role, content, run_id, sequence, mode, status, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, (SELECT COALESCE(MAX(sequence), 0) + 1 FROM session_messages WHERE session_id = ?), ?, ?, ?, ?)`).run(messageId, sessionId, input.role, content, input.runId ?? null, sessionId, input.mode ?? null, input.status ?? "complete", createdAt, now));
            (await this.db.prepare(`UPDATE work_sessions SET updated_at = ? WHERE session_id = ?`).run(now, sessionId));
            if (input.meta)
                return (await this.updateMessage(messageId, { meta: input.meta }));
            return (await this.getMessage(messageId));
        });
    }
    async updateMessage(messageId: string, patch: {
        content?: string;
        runId?: string | null;
        status?: "complete" | "streaming";
        meta?: Record<string, unknown>;
    }): Promise<SessionMessage | undefined> {
        return this.db.transaction(async () => {
            const m = (await this.getMessage(messageId));
            if (!m)
                return undefined;
            const content = patch.content !== undefined ? String(patch.content).slice(0, MAX_MESSAGE) : m.content;
            const meta = patch.meta !== undefined ? { ...(m.meta ?? {}), ...patch.meta } : m.meta;
            const now = Date.now();
            (await this.db.prepare(`UPDATE session_messages SET content = ?, run_id = ?, status = ?, meta_json = ?, updated_at = ? WHERE message_id = ?`)
                .run(content, patch.runId !== undefined ? patch.runId : m.runId, patch.status ?? m.status, meta ? JSON.stringify(meta).slice(0, 200000) : null, now, messageId));
            (await this.db.prepare(`UPDATE work_sessions SET updated_at = ? WHERE session_id = ?`).run(now, m.sessionId));
            return (await this.getMessage(messageId));
        });
    }
    /** Removes one message of a session (a regenerated reply replaces the old one). */
    async deleteMessage(sessionId: string, messageId: string): Promise<boolean> {
        return this.db.transaction(async () => {
            const r = (await this.db.prepare(`DELETE FROM session_messages WHERE message_id = ? AND session_id = ?`).run(messageId, sessionId));
            return Number(r.changes) > 0;
        });
    }
    async getMessage(messageId: string): Promise<SessionMessage | undefined> {
        return this.db.transaction(async () => {
            const r = (await this.db.prepare(`SELECT * FROM session_messages WHERE message_id = ?`).get(messageId)) as MessageRow | undefined;
            return r ? messageFromRow(r) : undefined;
        });
    }
    /** The conversation in order. `after` returns only messages past that sequence. */
    async messages(sessionId: string, after = 0): Promise<SessionMessage[]> {
        return this.db.transaction(async () => {
            const rows = (await this.db.prepare(`SELECT * FROM session_messages WHERE session_id = ? AND sequence > ? ORDER BY sequence ASC`).all(sessionId, after)) as unknown as MessageRow[];
            return rows.map(messageFromRow);
        });
    }
    /** For the chat list: how many messages, and the newest one's text. */
    async messageSummary(sessionId: string): Promise<{
        messageCount: number;
        lastMessage: string;
    }> {
        return this.db.transaction(async () => {
            const c = (await this.db.prepare(`SELECT COUNT(*) AS n FROM session_messages WHERE session_id = ?`).get(sessionId)) as {
                n: number;
            };
            const last = (await this.db.prepare(`SELECT content FROM session_messages WHERE session_id = ? AND content != '' ORDER BY sequence DESC LIMIT 1`).get(sessionId)) as {
                content: string;
            } | undefined;
            return { messageCount: Number(c.n), lastMessage: (last?.content ?? "").slice(0, 160) };
        });
    }
    /** The message that started a run (its instruction), if stored. */
    async messageOfRun(runId: string, role: SessionMessageRole = "user"): Promise<SessionMessage | undefined> {
        return this.db.transaction(async () => {
            const r = (await this.db.prepare(`SELECT * FROM session_messages WHERE run_id = ? AND role = ? ORDER BY sequence ASC LIMIT 1`).get(runId, role)) as MessageRow | undefined;
            return r ? messageFromRow(r) : undefined;
        });
    }
}
