// packages/ai-core/src/adapters/mockAdapter.ts
// NOT IMPLEMENTED AS A REAL MODEL. This exists purely so ORVYN is runnable
// and demo-able with zero external dependencies before a real model
// (Ollama / vLLM / custom API) is wired up in Settings > AI Models.
import { AIModelProvider, AIRequest, AIResponse, AIChunk, ModelConfig } from "../types";

export class MockAdapter implements AIModelProvider {
  constructor(public readonly config: ModelConfig) {}

  async generate(request: AIRequest): Promise<AIResponse> {
    const lastUser = [...request.messages].reverse().find((m) => m.role === "user");
    const userText = lastUser?.content ?? "";

    // Scripted Agent tool-calling behavior: when tools are offered, walk a
    // fixed two-step demo (list_directory, then write_file) so the Agent
    // loop's tool-execution / approval-pause / resume mechanics are
    // testable end-to-end without a real reasoning model. This is a demo
    // fixture, not real planning — a real model decides its own tool calls.
    if (request.tools && request.tools.length > 0) {
      const toolMessages = request.messages.filter((m) => m.role === "tool");
      const hasTool = (name: string) => request.tools!.some((t) => t.name === name);

      if (toolMessages.length === 0 && hasTool("list_directory")) {
        return {
          content: "",
          toolCalls: [{ id: "call_1", name: "list_directory", arguments: { path: "." } }],
          finishReason: "tool_call",
        };
      }
      if (toolMessages.length === 1 && hasTool("write_file")) {
        return {
          content: "",
          toolCalls: [
            {
              id: "call_2",
              name: "write_file",
              arguments: {
                path: "AGENT_NOTES.md",
                content: `# Agent run (mock)\n\nInstruction: ${userText}\n\nListed the project directory, then wrote this file as a demo of the tool-calling loop.\n`,
              },
            },
          ],
          finishReason: "tool_call",
        };
      }
      const lastTool = toolMessages[toolMessages.length - 1];
      return {
        content: `[MOCK AGENT] Finished after using tools. Last tool result: ${lastTool?.content?.slice(0, 200) ?? "(none)"}`,
        finishReason: "stop",
      };
    }

    // Scripted inline-edit behavior: echo the selection with a marker comment
    // so the Ctrl+K diff pipeline is verifiable without a real model.
    if (userText.includes("inline code edit")) {
      const sel = userText.match(/Selected code[^:]*:\n([\s\S]*?)\n\nInstruction:/);
      const instr = userText.match(/Instruction:\s*(.*)$/);
      const body = sel ? sel[1] : "";
      return {
        content: `// [MOCK EDIT] ${instr ? instr[1] : ""}\n${body}`,
        finishReason: "stop",
      };
    }

    // Scripted Composer behavior: when asked for the Composer JSON contract,
    // return a valid, deterministic multi-file plan so the Composer pipeline
    // is testable end-to-end without a real model. Clearly a demo fixture,
    // not real code generation.
    if (userText.includes('"files"') && userText.includes("JSON object")) {
      const instructionMatch = userText.match(/User request:\s*([\s\S]*)$/);
      const instruction = instructionMatch ? instructionMatch[1].trim() : "the requested change";
      const plan = {
        summary: `[MOCK] Composer plan for: ${instruction.slice(0, 80)}`,
        files: [
          {
            path: "COMPOSER_CHANGE.md",
            content: `# Composer change\n\nRequested: ${instruction}\n\nThis file was created by the mock model to demonstrate the Composer pipeline end-to-end. Configure a real model in Settings > AI Models to get actual code changes.\n`,
          },
          {
            path: "src/composer-demo.ts",
            content: `// Generated by ORVYN Composer (mock model)\n// Request: ${instruction}\nexport function composerDemo(): string {\n  return "replace me with real generated code once a real model is configured";\n}\n`,
          },
        ],
      };
      return { content: JSON.stringify(plan), finishReason: "stop" };
    }

    return {
      content: `[MOCK MODEL — no real model configured yet]\n\nYou said: "${userText}"\n\nI can still chat, plan, and (via Agent/Composer) write into the built-in workspace without you opening a folder. Configure a real model in AI Models to replace this placeholder.`,
      finishReason: "stop",
    };
  }

  async *stream(request: AIRequest): AsyncIterable<AIChunk> {
    const { content } = await this.generate(request);
    for (const word of content.split(" ")) {
      yield { delta: word + " ", done: false };
      await new Promise((r) => setTimeout(r, 15));
    }
    yield { delta: "", done: true };
  }

  async healthCheck() {
    return { status: "online" as const, latencyMs: 1 };
  }

  supportsTools(): boolean {
    return false;
  }

  supportsVision(): boolean {
    return false;
  }
}
