import { Pool, type PoolClient } from "pg";
import { AUTH_INDEXES, AUTH_TABLES, AUTH_UNIQUE_KEYS } from "./authSchema";
import { authSnapshotFingerprint, validateAuthSnapshot, type AuthSnapshot, type AuthRow } from "./AuthStorageSnapshot";

const LOCK = "SELECT pg_advisory_xact_lock(730021, 2)";

/** Complete authentication migration target. Live auth routing is deliberately not switched here. */
export class PostgresAuthStorage {
  private pool: Pool;
  constructor(url: string) {
    if (!url) throw new Error("Authentication storage requires a PostgreSQL URL");
    this.pool = new Pool({ connectionString:url, max:4, connectionTimeoutMillis:5000,
      statement_timeout:10000, lock_timeout:5000, idleTimeoutMillis:30000 });
  }

  private async transaction<T>(operation: (client:PoolClient) => Promise<T>): Promise<T> {
    const client = await this.pool.connect();
    let discard: Error | undefined;
    try {
      await client.query("BEGIN");
      await client.query(LOCK);
      const result = await operation(client);
      await client.query("COMMIT");
      return result;
    } catch (error) {
      try { await client.query("ROLLBACK"); } catch { discard = new Error("Authentication transaction connection failed"); }
      throw error;
    } finally { client.release(discard); }
  }

  async init(): Promise<void> {
    await this.transaction(async client => {
      await client.query("CREATE SCHEMA IF NOT EXISTS orvyn_auth");
      await client.query("CREATE TABLE IF NOT EXISTS orvyn_auth.migrations(version INTEGER PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())");
      const applied = await client.query("SELECT version FROM orvyn_auth.migrations ORDER BY version");
      if (applied.rows.some(row => row.version !== 1)) throw new Error("Unsupported authentication storage version");
      if (applied.rowCount) return;
      for (const table of AUTH_TABLES) {
        // SQL comes exclusively from the checked-in contract, never from imported files.
        await client.query(table.sql.replace(/CREATE TABLE(?: IF NOT EXISTS)?\s+\w+/i,
          `CREATE TABLE orvyn_auth."${table.name}"`).replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g,
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY").replace(/\bINTEGER\b/g, "BIGINT"));
      }
      for (const sql of AUTH_INDEXES) await client.query(sql.replace(/\bON\s+(\w+)/i, 'ON orvyn_auth."$1"'));
      await client.query("CREATE TABLE orvyn_auth.imports(fingerprint TEXT PRIMARY KEY, imported_at TIMESTAMPTZ NOT NULL DEFAULT now())");
      await client.query("CREATE TABLE orvyn_auth.source_sequences(name TEXT PRIMARY KEY,seq BIGINT NOT NULL)");
      await client.query(`CREATE FUNCTION orvyn_auth.reject_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS
        $$ BEGIN RAISE EXCEPTION 'admin_audit is append-only'; END; $$;
        CREATE TRIGGER admin_audit_append_only BEFORE UPDATE OR DELETE ON orvyn_auth.admin_audit
        FOR EACH ROW EXECUTE FUNCTION orvyn_auth.reject_audit_mutation();
        CREATE TRIGGER admin_audit_no_truncate BEFORE TRUNCATE ON orvyn_auth.admin_audit
        FOR EACH STATEMENT EXECUTE FUNCTION orvyn_auth.reject_audit_mutation()`);
      await client.query("INSERT INTO orvyn_auth.migrations(version) VALUES (1)");
    });
  }

  private async read(client: PoolClient): Promise<AuthSnapshot> {
    // Keep the cross-table view consistent even if an operator writes outside this repository.
    await client.query(`LOCK TABLE ${AUTH_TABLES.map(table => `orvyn_auth."${table.name}"`).join(",")},orvyn_auth.source_sequences IN SHARE ROW EXCLUSIVE MODE`);
    const version = await client.query("SELECT version FROM orvyn_auth.migrations ORDER BY version");
    if (version.rows.length !== 1 || version.rows[0].version !== 1) throw new Error("Unsupported authentication storage version");
    const columns = await client.query("SELECT table_name,column_name,data_type,is_nullable FROM information_schema.columns WHERE table_schema='orvyn_auth'");
    const keys = await client.query(`SELECT c.relname AS table_name,array_agg(a.attname::text ORDER BY k.ord) AS columns
      FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace
      CROSS JOIN LATERAL unnest(con.conkey) WITH ORDINALITY k(attnum,ord)
      JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum=k.attnum
      WHERE n.nspname='orvyn_auth' AND con.contype IN ('p','u') GROUP BY c.relname,con.oid`);
    for (const table of AUTH_TABLES) {
      const actual = columns.rows.filter(row => row.table_name === table.name);
      if (actual.length !== table.columns.length || table.columns.some(column => !actual.some(row =>
        row.column_name === column.name && row.data_type === (column.type === "INTEGER" ? "bigint" : "text") &&
        row.is_nullable === (column.notNull || column.primaryKey ? "NO" : "YES")))) {
        throw new Error(`PostgreSQL authentication schema differs: ${table.name}`);
      }
      const canonical = (values: readonly (readonly string[])[]) => JSON.stringify(Array.from(new Set(values.map(value => JSON.stringify(value)))).sort());
      if (canonical(keys.rows.filter(row => row.table_name === table.name).map(row => row.columns)) !== canonical(AUTH_UNIQUE_KEYS[table.name])) {
        throw new Error(`PostgreSQL authentication uniqueness differs: ${table.name}`);
      }
    }
    const trigger = await client.query(`SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace
      WHERE n.nspname='orvyn_auth' AND c.relname='admin_audit' AND t.tgname IN ('admin_audit_append_only','admin_audit_no_truncate') AND t.tgenabled='O'`);
    if (trigger.rowCount !== 2) throw new Error("PostgreSQL authentication audit protections differ");
    const snapshot: AuthSnapshot = {};
    for (const table of AUTH_TABLES) {
      const result = await client.query(`SELECT * FROM orvyn_auth."${table.name}"`);
      snapshot[table.name] = result.rows.map(row => {
        const normalized: AuthRow = {};
        for (const column of table.columns) normalized[column.name] = row[column.name] === null ? null :
          column.type === "INTEGER" ? Number(row[column.name]) : row[column.name];
        return normalized;
      });
    }
    const sequence = await client.query("SELECT last_value,is_called FROM orvyn_auth.admin_audit_seq_seq");
    const recorded = await client.query("SELECT name,seq FROM orvyn_auth.source_sequences ORDER BY name");
    if (recorded.rows.some(row => row.name !== "admin_audit")) throw new Error("Unsupported authentication sequence");
    const highWater = Number(sequence.rows[0].last_value) - (sequence.rows[0].is_called ? 0 : 1);
    snapshot.__sequences = highWater > 0 || recorded.rowCount ? [{ name:"admin_audit", seq:highWater }] : [];
    validateAuthSnapshot(snapshot);
    return snapshot;
  }

  async verify(snapshot: AuthSnapshot): Promise<{ matches:boolean; fingerprint:string; counts:Record<string,number> }> {
    const fingerprint = authSnapshotFingerprint(snapshot);
    return this.transaction(async client => {
      const stored = await this.read(client);
      return { matches:authSnapshotFingerprint(stored) === fingerprint, fingerprint,
        counts:Object.fromEntries(AUTH_TABLES.map(table => [table.name, stored[table.name].length])) };
    });
  }

  /** Private migration/restore tooling only: the returned records contain account secrets. */
  async exportSnapshot(): Promise<AuthSnapshot> { return this.transaction(client => this.read(client)); }

  /** Seed only an empty target; repeat of identical data is safe, differing data is never overwritten. */
  async importSnapshot(snapshot: AuthSnapshot): Promise<{ imported:boolean; fingerprint:string }> {
    const fingerprint = authSnapshotFingerprint(snapshot);
    return this.transaction(async client => {
      const current = await this.read(client);
      const imported = await client.query("SELECT 1 FROM orvyn_auth.imports LIMIT 1");
      const occupied = imported.rowCount || current.__sequences.length || AUTH_TABLES.some(table => current[table.name].length > 0);
      if (occupied) {
        if (authSnapshotFingerprint(current) !== fingerprint) throw new Error("Authentication target differs; refusing to overwrite existing records");
        return { imported:false, fingerprint };
      }
      for (const table of AUTH_TABLES) {
        const columns = table.columns.map(column => `"${column.name}"`).join(",");
        const placeholders = table.columns.map((_, index) => `$${index + 1}`).join(",");
        for (const row of snapshot[table.name]) await client.query(
          `INSERT INTO orvyn_auth."${table.name}"(${columns}) VALUES (${placeholders})`, table.columns.map(column => row[column.name]));
      }
      for (const row of snapshot.__sequences) {
        await client.query("INSERT INTO orvyn_auth.source_sequences(name,seq) VALUES ($1,$2)", [row.name,row.seq]);
      }
      // RESTART is transactional, unlike setval/nextval: a failed import also restores
      // the counter. Explicit inserted audit ids do not consume the identity sequence.
      const highWater = snapshot.__sequences.find(row => row.name === "admin_audit")?.seq ?? 0;
      await client.query(`ALTER SEQUENCE orvyn_auth.admin_audit_seq_seq RESTART WITH ${Number(highWater) + 1}`);
      if (authSnapshotFingerprint(await this.read(client)) !== fingerprint) throw new Error("Authentication content verification failed");
      await client.query("INSERT INTO orvyn_auth.imports(fingerprint) VALUES ($1)", [fingerprint]);
      return { imported:true, fingerprint };
    });
  }

  async close(): Promise<void> { await this.pool.end(); }
}
